[2025-02-07T00:05:54.502+0000] {processor.py:157} INFO - Started process (PID=3454) to work on /opt/airflow/dags/gx.py
[2025-02-07T00:05:54.504+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/gx.py for tasks to queue
[2025-02-07T00:05:54.508+0000] {logging_mixin.py:151} INFO - [2025-02-07T00:05:54.507+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/gx.py
[2025-02-07T00:05:56.621+0000] {logging_mixin.py:151} INFO - [2025-02-07T00:05:56.620+0000] {warnings.py:109} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:103: UserWarning: You have an incompatible version of 'pyarrow' installed (11.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
  warn_incompatible_dep(
[2025-02-07T00:05:57.007+0000] {logging_mixin.py:151} INFO - [2025-02-07T00:05:57.005+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/gx.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gx.py", line 3, in <module>
    from great_expectations_provider.operators.great_expectations import (
  File "/home/airflow/.local/lib/python3.8/site-packages/great_expectations_provider/operators/great_expectations.py", line 30, in <module>
    from great_expectations.checkpoint.types.checkpoint_result import CheckpointResult
ModuleNotFoundError: No module named 'great_expectations.checkpoint.types'
[2025-02-07T00:05:57.007+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/gx.py
[2025-02-07T00:05:57.020+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/gx.py took 2.521 seconds
[2025-02-07T00:06:27.205+0000] {processor.py:157} INFO - Started process (PID=3475) to work on /opt/airflow/dags/gx.py
[2025-02-07T00:06:27.206+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/gx.py for tasks to queue
[2025-02-07T00:06:27.209+0000] {logging_mixin.py:151} INFO - [2025-02-07T00:06:27.208+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/gx.py
[2025-02-07T00:06:29.035+0000] {logging_mixin.py:151} INFO - [2025-02-07T00:06:29.034+0000] {warnings.py:109} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:103: UserWarning: You have an incompatible version of 'pyarrow' installed (11.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
  warn_incompatible_dep(
[2025-02-07T00:06:29.389+0000] {logging_mixin.py:151} INFO - [2025-02-07T00:06:29.388+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/gx.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gx.py", line 3, in <module>
    from great_expectations_provider.operators.great_expectations import (
  File "/home/airflow/.local/lib/python3.8/site-packages/great_expectations_provider/operators/great_expectations.py", line 30, in <module>
    from great_expectations.checkpoint.types.checkpoint_result import CheckpointResult
ModuleNotFoundError: No module named 'great_expectations.checkpoint.types'
[2025-02-07T00:06:29.389+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/gx.py
[2025-02-07T00:06:29.412+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/gx.py took 2.210 seconds
[2025-02-07T00:06:59.599+0000] {processor.py:157} INFO - Started process (PID=3496) to work on /opt/airflow/dags/gx.py
[2025-02-07T00:06:59.600+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/gx.py for tasks to queue
[2025-02-07T00:06:59.603+0000] {logging_mixin.py:151} INFO - [2025-02-07T00:06:59.602+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/gx.py
[2025-02-07T00:07:01.218+0000] {logging_mixin.py:151} INFO - [2025-02-07T00:07:01.217+0000] {warnings.py:109} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:103: UserWarning: You have an incompatible version of 'pyarrow' installed (11.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
  warn_incompatible_dep(
[2025-02-07T00:07:01.559+0000] {logging_mixin.py:151} INFO - [2025-02-07T00:07:01.557+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/gx.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gx.py", line 3, in <module>
    from great_expectations_provider.operators.great_expectations import (
  File "/home/airflow/.local/lib/python3.8/site-packages/great_expectations_provider/operators/great_expectations.py", line 30, in <module>
    from great_expectations.checkpoint.types.checkpoint_result import CheckpointResult
ModuleNotFoundError: No module named 'great_expectations.checkpoint.types'
[2025-02-07T00:07:01.559+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/gx.py
[2025-02-07T00:07:01.580+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/gx.py took 1.984 seconds
[2025-02-07T00:07:31.633+0000] {processor.py:157} INFO - Started process (PID=3517) to work on /opt/airflow/dags/gx.py
[2025-02-07T00:07:31.634+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/gx.py for tasks to queue
[2025-02-07T00:07:31.637+0000] {logging_mixin.py:151} INFO - [2025-02-07T00:07:31.637+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/gx.py
[2025-02-07T00:07:33.441+0000] {logging_mixin.py:151} INFO - [2025-02-07T00:07:33.440+0000] {warnings.py:109} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:103: UserWarning: You have an incompatible version of 'pyarrow' installed (11.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
  warn_incompatible_dep(
[2025-02-07T00:07:33.832+0000] {logging_mixin.py:151} INFO - [2025-02-07T00:07:33.830+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/gx.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gx.py", line 3, in <module>
    from great_expectations_provider.operators.great_expectations import (
  File "/home/airflow/.local/lib/python3.8/site-packages/great_expectations_provider/operators/great_expectations.py", line 30, in <module>
    from great_expectations.checkpoint.types.checkpoint_result import CheckpointResult
ModuleNotFoundError: No module named 'great_expectations.checkpoint.types'
[2025-02-07T00:07:33.832+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/gx.py
[2025-02-07T00:07:33.853+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/gx.py took 2.223 seconds
[2025-02-07T00:08:03.968+0000] {processor.py:157} INFO - Started process (PID=3538) to work on /opt/airflow/dags/gx.py
[2025-02-07T00:08:03.969+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/gx.py for tasks to queue
[2025-02-07T00:08:03.971+0000] {logging_mixin.py:151} INFO - [2025-02-07T00:08:03.971+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/gx.py
[2025-02-07T00:08:05.656+0000] {logging_mixin.py:151} INFO - [2025-02-07T00:08:05.655+0000] {warnings.py:109} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:103: UserWarning: You have an incompatible version of 'pyarrow' installed (11.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
  warn_incompatible_dep(
[2025-02-07T00:08:06.041+0000] {logging_mixin.py:151} INFO - [2025-02-07T00:08:06.039+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/gx.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gx.py", line 3, in <module>
    from great_expectations_provider.operators.great_expectations import (
  File "/home/airflow/.local/lib/python3.8/site-packages/great_expectations_provider/operators/great_expectations.py", line 30, in <module>
    from great_expectations.checkpoint.types.checkpoint_result import CheckpointResult
ModuleNotFoundError: No module named 'great_expectations.checkpoint.types'
[2025-02-07T00:08:06.041+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/gx.py
[2025-02-07T00:08:06.064+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/gx.py took 2.099 seconds
[2025-02-07T00:08:36.196+0000] {processor.py:157} INFO - Started process (PID=3559) to work on /opt/airflow/dags/gx.py
[2025-02-07T00:08:36.197+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/gx.py for tasks to queue
[2025-02-07T00:08:36.199+0000] {logging_mixin.py:151} INFO - [2025-02-07T00:08:36.199+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/gx.py
[2025-02-07T00:08:38.058+0000] {logging_mixin.py:151} INFO - [2025-02-07T00:08:38.057+0000] {warnings.py:109} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:103: UserWarning: You have an incompatible version of 'pyarrow' installed (11.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
  warn_incompatible_dep(
[2025-02-07T00:08:38.471+0000] {logging_mixin.py:151} INFO - [2025-02-07T00:08:38.470+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/gx.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gx.py", line 3, in <module>
    from great_expectations_provider.operators.great_expectations import (
  File "/home/airflow/.local/lib/python3.8/site-packages/great_expectations_provider/operators/great_expectations.py", line 30, in <module>
    from great_expectations.checkpoint.types.checkpoint_result import CheckpointResult
ModuleNotFoundError: No module named 'great_expectations.checkpoint.types'
[2025-02-07T00:08:38.472+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/gx.py
[2025-02-07T00:08:38.493+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/gx.py took 2.300 seconds
[2025-02-07T00:09:08.642+0000] {processor.py:157} INFO - Started process (PID=3580) to work on /opt/airflow/dags/gx.py
[2025-02-07T00:09:08.643+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/gx.py for tasks to queue
[2025-02-07T00:09:08.645+0000] {logging_mixin.py:151} INFO - [2025-02-07T00:09:08.644+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/gx.py
[2025-02-07T00:09:10.467+0000] {logging_mixin.py:151} INFO - [2025-02-07T00:09:10.467+0000] {warnings.py:109} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:103: UserWarning: You have an incompatible version of 'pyarrow' installed (11.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
  warn_incompatible_dep(
[2025-02-07T00:09:10.865+0000] {logging_mixin.py:151} INFO - [2025-02-07T00:09:10.864+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/gx.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gx.py", line 3, in <module>
    from great_expectations_provider.operators.great_expectations import (
  File "/home/airflow/.local/lib/python3.8/site-packages/great_expectations_provider/operators/great_expectations.py", line 30, in <module>
    from great_expectations.checkpoint.types.checkpoint_result import CheckpointResult
ModuleNotFoundError: No module named 'great_expectations.checkpoint.types'
[2025-02-07T00:09:10.865+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/gx.py
[2025-02-07T00:09:10.887+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/gx.py took 2.249 seconds
[2025-02-07T00:09:41.029+0000] {processor.py:157} INFO - Started process (PID=3601) to work on /opt/airflow/dags/gx.py
[2025-02-07T00:09:41.030+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/gx.py for tasks to queue
[2025-02-07T00:09:41.033+0000] {logging_mixin.py:151} INFO - [2025-02-07T00:09:41.033+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/gx.py
[2025-02-07T00:09:42.982+0000] {logging_mixin.py:151} INFO - [2025-02-07T00:09:42.981+0000] {warnings.py:109} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:103: UserWarning: You have an incompatible version of 'pyarrow' installed (11.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
  warn_incompatible_dep(
[2025-02-07T00:09:43.413+0000] {logging_mixin.py:151} INFO - [2025-02-07T00:09:43.412+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/gx.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gx.py", line 3, in <module>
    from great_expectations_provider.operators.great_expectations import (
  File "/home/airflow/.local/lib/python3.8/site-packages/great_expectations_provider/operators/great_expectations.py", line 30, in <module>
    from great_expectations.checkpoint.types.checkpoint_result import CheckpointResult
ModuleNotFoundError: No module named 'great_expectations.checkpoint.types'
[2025-02-07T00:09:43.413+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/gx.py
[2025-02-07T00:09:43.437+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/gx.py took 2.411 seconds
[2025-02-07T00:10:13.589+0000] {processor.py:157} INFO - Started process (PID=3622) to work on /opt/airflow/dags/gx.py
[2025-02-07T00:10:13.589+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/gx.py for tasks to queue
[2025-02-07T00:10:13.592+0000] {logging_mixin.py:151} INFO - [2025-02-07T00:10:13.592+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/gx.py
[2025-02-07T00:10:15.487+0000] {logging_mixin.py:151} INFO - [2025-02-07T00:10:15.486+0000] {warnings.py:109} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:103: UserWarning: You have an incompatible version of 'pyarrow' installed (11.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
  warn_incompatible_dep(
[2025-02-07T00:10:15.890+0000] {logging_mixin.py:151} INFO - [2025-02-07T00:10:15.889+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/gx.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gx.py", line 3, in <module>
    from great_expectations_provider.operators.great_expectations import (
  File "/home/airflow/.local/lib/python3.8/site-packages/great_expectations_provider/operators/great_expectations.py", line 30, in <module>
    from great_expectations.checkpoint.types.checkpoint_result import CheckpointResult
ModuleNotFoundError: No module named 'great_expectations.checkpoint.types'
[2025-02-07T00:10:15.890+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/gx.py
[2025-02-07T00:10:15.912+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/gx.py took 2.326 seconds
[2025-02-07T00:10:46.053+0000] {processor.py:157} INFO - Started process (PID=3643) to work on /opt/airflow/dags/gx.py
[2025-02-07T00:10:46.054+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/gx.py for tasks to queue
[2025-02-07T00:10:46.056+0000] {logging_mixin.py:151} INFO - [2025-02-07T00:10:46.056+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/gx.py
[2025-02-07T00:10:47.900+0000] {logging_mixin.py:151} INFO - [2025-02-07T00:10:47.899+0000] {warnings.py:109} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:103: UserWarning: You have an incompatible version of 'pyarrow' installed (11.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
  warn_incompatible_dep(
[2025-02-07T00:10:48.308+0000] {logging_mixin.py:151} INFO - [2025-02-07T00:10:48.307+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/gx.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gx.py", line 3, in <module>
    from great_expectations_provider.operators.great_expectations import (
  File "/home/airflow/.local/lib/python3.8/site-packages/great_expectations_provider/operators/great_expectations.py", line 30, in <module>
    from great_expectations.checkpoint.types.checkpoint_result import CheckpointResult
ModuleNotFoundError: No module named 'great_expectations.checkpoint.types'
[2025-02-07T00:10:48.308+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/gx.py
[2025-02-07T00:10:48.330+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/gx.py took 2.281 seconds
[2025-02-07T00:11:18.472+0000] {processor.py:157} INFO - Started process (PID=3664) to work on /opt/airflow/dags/gx.py
[2025-02-07T00:11:18.473+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/gx.py for tasks to queue
[2025-02-07T00:11:18.475+0000] {logging_mixin.py:151} INFO - [2025-02-07T00:11:18.475+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/gx.py
[2025-02-07T00:11:20.369+0000] {logging_mixin.py:151} INFO - [2025-02-07T00:11:20.368+0000] {warnings.py:109} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:103: UserWarning: You have an incompatible version of 'pyarrow' installed (11.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
  warn_incompatible_dep(
[2025-02-07T00:11:20.784+0000] {logging_mixin.py:151} INFO - [2025-02-07T00:11:20.783+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/gx.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gx.py", line 3, in <module>
    from great_expectations_provider.operators.great_expectations import (
  File "/home/airflow/.local/lib/python3.8/site-packages/great_expectations_provider/operators/great_expectations.py", line 30, in <module>
    from great_expectations.checkpoint.types.checkpoint_result import CheckpointResult
ModuleNotFoundError: No module named 'great_expectations.checkpoint.types'
[2025-02-07T00:11:20.784+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/gx.py
[2025-02-07T00:11:20.810+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/gx.py took 2.341 seconds
[2025-02-07T00:11:50.992+0000] {processor.py:157} INFO - Started process (PID=3685) to work on /opt/airflow/dags/gx.py
[2025-02-07T00:11:50.992+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/gx.py for tasks to queue
[2025-02-07T00:11:50.995+0000] {logging_mixin.py:151} INFO - [2025-02-07T00:11:50.995+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/gx.py
[2025-02-07T00:11:52.869+0000] {logging_mixin.py:151} INFO - [2025-02-07T00:11:52.868+0000] {warnings.py:109} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:103: UserWarning: You have an incompatible version of 'pyarrow' installed (11.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
  warn_incompatible_dep(
[2025-02-07T00:11:53.271+0000] {logging_mixin.py:151} INFO - [2025-02-07T00:11:53.270+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/gx.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gx.py", line 3, in <module>
    from great_expectations_provider.operators.great_expectations import (
  File "/home/airflow/.local/lib/python3.8/site-packages/great_expectations_provider/operators/great_expectations.py", line 30, in <module>
    from great_expectations.checkpoint.types.checkpoint_result import CheckpointResult
ModuleNotFoundError: No module named 'great_expectations.checkpoint.types'
[2025-02-07T00:11:53.272+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/gx.py
[2025-02-07T00:11:53.294+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/gx.py took 2.305 seconds
[2025-02-07T00:12:23.438+0000] {processor.py:157} INFO - Started process (PID=3706) to work on /opt/airflow/dags/gx.py
[2025-02-07T00:12:23.440+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/gx.py for tasks to queue
[2025-02-07T00:12:23.443+0000] {logging_mixin.py:151} INFO - [2025-02-07T00:12:23.442+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/gx.py
[2025-02-07T00:12:25.326+0000] {logging_mixin.py:151} INFO - [2025-02-07T00:12:25.326+0000] {warnings.py:109} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:103: UserWarning: You have an incompatible version of 'pyarrow' installed (11.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
  warn_incompatible_dep(
[2025-02-07T00:12:25.742+0000] {logging_mixin.py:151} INFO - [2025-02-07T00:12:25.740+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/gx.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gx.py", line 3, in <module>
    from great_expectations_provider.operators.great_expectations import (
  File "/home/airflow/.local/lib/python3.8/site-packages/great_expectations_provider/operators/great_expectations.py", line 30, in <module>
    from great_expectations.checkpoint.types.checkpoint_result import CheckpointResult
ModuleNotFoundError: No module named 'great_expectations.checkpoint.types'
[2025-02-07T00:12:25.742+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/gx.py
[2025-02-07T00:12:25.765+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/gx.py took 2.329 seconds
[2025-02-07T00:12:55.905+0000] {processor.py:157} INFO - Started process (PID=3734) to work on /opt/airflow/dags/gx.py
[2025-02-07T00:12:55.906+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/gx.py for tasks to queue
[2025-02-07T00:12:55.908+0000] {logging_mixin.py:151} INFO - [2025-02-07T00:12:55.908+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/gx.py
[2025-02-07T00:12:57.760+0000] {logging_mixin.py:151} INFO - [2025-02-07T00:12:57.759+0000] {warnings.py:109} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:103: UserWarning: You have an incompatible version of 'pyarrow' installed (11.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
  warn_incompatible_dep(
[2025-02-07T00:12:58.161+0000] {logging_mixin.py:151} INFO - [2025-02-07T00:12:58.160+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/gx.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gx.py", line 3, in <module>
    from great_expectations_provider.operators.great_expectations import (
  File "/home/airflow/.local/lib/python3.8/site-packages/great_expectations_provider/operators/great_expectations.py", line 30, in <module>
    from great_expectations.checkpoint.types.checkpoint_result import CheckpointResult
ModuleNotFoundError: No module named 'great_expectations.checkpoint.types'
[2025-02-07T00:12:58.161+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/gx.py
[2025-02-07T00:12:58.175+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/gx.py took 2.273 seconds
[2025-02-07T00:13:28.310+0000] {processor.py:157} INFO - Started process (PID=3755) to work on /opt/airflow/dags/gx.py
[2025-02-07T00:13:28.311+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/gx.py for tasks to queue
[2025-02-07T00:13:28.314+0000] {logging_mixin.py:151} INFO - [2025-02-07T00:13:28.313+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/gx.py
[2025-02-07T00:13:30.140+0000] {logging_mixin.py:151} INFO - [2025-02-07T00:13:30.139+0000] {warnings.py:109} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:103: UserWarning: You have an incompatible version of 'pyarrow' installed (11.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
  warn_incompatible_dep(
[2025-02-07T00:13:30.530+0000] {logging_mixin.py:151} INFO - [2025-02-07T00:13:30.529+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/gx.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gx.py", line 3, in <module>
    from great_expectations_provider.operators.great_expectations import (
  File "/home/airflow/.local/lib/python3.8/site-packages/great_expectations_provider/operators/great_expectations.py", line 30, in <module>
    from great_expectations.checkpoint.types.checkpoint_result import CheckpointResult
ModuleNotFoundError: No module named 'great_expectations.checkpoint.types'
[2025-02-07T00:13:30.531+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/gx.py
[2025-02-07T00:13:30.544+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/gx.py took 2.237 seconds
[2025-02-07T00:14:00.685+0000] {processor.py:157} INFO - Started process (PID=3776) to work on /opt/airflow/dags/gx.py
[2025-02-07T00:14:00.686+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/gx.py for tasks to queue
[2025-02-07T00:14:00.689+0000] {logging_mixin.py:151} INFO - [2025-02-07T00:14:00.689+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/gx.py
[2025-02-07T00:14:02.628+0000] {logging_mixin.py:151} INFO - [2025-02-07T00:14:02.628+0000] {warnings.py:109} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:103: UserWarning: You have an incompatible version of 'pyarrow' installed (11.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
  warn_incompatible_dep(
[2025-02-07T00:14:03.042+0000] {logging_mixin.py:151} INFO - [2025-02-07T00:14:03.041+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/gx.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gx.py", line 3, in <module>
    from great_expectations_provider.operators.great_expectations import (
  File "/home/airflow/.local/lib/python3.8/site-packages/great_expectations_provider/operators/great_expectations.py", line 30, in <module>
    from great_expectations.checkpoint.types.checkpoint_result import CheckpointResult
ModuleNotFoundError: No module named 'great_expectations.checkpoint.types'
[2025-02-07T00:14:03.042+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/gx.py
[2025-02-07T00:14:03.066+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/gx.py took 2.384 seconds
[2025-02-07T00:14:33.262+0000] {processor.py:157} INFO - Started process (PID=3797) to work on /opt/airflow/dags/gx.py
[2025-02-07T00:14:33.263+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/gx.py for tasks to queue
[2025-02-07T00:14:33.265+0000] {logging_mixin.py:151} INFO - [2025-02-07T00:14:33.265+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/gx.py
[2025-02-07T00:14:35.074+0000] {logging_mixin.py:151} INFO - [2025-02-07T00:14:35.074+0000] {warnings.py:109} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:103: UserWarning: You have an incompatible version of 'pyarrow' installed (11.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
  warn_incompatible_dep(
[2025-02-07T00:14:35.489+0000] {logging_mixin.py:151} INFO - [2025-02-07T00:14:35.488+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/gx.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gx.py", line 3, in <module>
    from great_expectations_provider.operators.great_expectations import (
  File "/home/airflow/.local/lib/python3.8/site-packages/great_expectations_provider/operators/great_expectations.py", line 30, in <module>
    from great_expectations.checkpoint.types.checkpoint_result import CheckpointResult
ModuleNotFoundError: No module named 'great_expectations.checkpoint.types'
[2025-02-07T00:14:35.490+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/gx.py
[2025-02-07T00:14:35.514+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/gx.py took 2.255 seconds
[2025-02-07T00:15:05.707+0000] {processor.py:157} INFO - Started process (PID=3818) to work on /opt/airflow/dags/gx.py
[2025-02-07T00:15:05.709+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/gx.py for tasks to queue
[2025-02-07T00:15:05.711+0000] {logging_mixin.py:151} INFO - [2025-02-07T00:15:05.711+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/gx.py
[2025-02-07T00:15:07.498+0000] {logging_mixin.py:151} INFO - [2025-02-07T00:15:07.497+0000] {warnings.py:109} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:103: UserWarning: You have an incompatible version of 'pyarrow' installed (11.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
  warn_incompatible_dep(
[2025-02-07T00:15:07.878+0000] {logging_mixin.py:151} INFO - [2025-02-07T00:15:07.877+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/gx.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gx.py", line 3, in <module>
    from great_expectations_provider.operators.great_expectations import (
  File "/home/airflow/.local/lib/python3.8/site-packages/great_expectations_provider/operators/great_expectations.py", line 30, in <module>
    from great_expectations.checkpoint.types.checkpoint_result import CheckpointResult
ModuleNotFoundError: No module named 'great_expectations.checkpoint.types'
[2025-02-07T00:15:07.879+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/gx.py
[2025-02-07T00:15:07.911+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/gx.py took 2.206 seconds
[2025-02-07T00:15:38.134+0000] {processor.py:157} INFO - Started process (PID=3839) to work on /opt/airflow/dags/gx.py
[2025-02-07T00:15:38.135+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/gx.py for tasks to queue
[2025-02-07T00:15:38.137+0000] {logging_mixin.py:151} INFO - [2025-02-07T00:15:38.137+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/gx.py
[2025-02-07T00:15:39.796+0000] {logging_mixin.py:151} INFO - [2025-02-07T00:15:39.795+0000] {warnings.py:109} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:103: UserWarning: You have an incompatible version of 'pyarrow' installed (11.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
  warn_incompatible_dep(
[2025-02-07T00:15:40.170+0000] {logging_mixin.py:151} INFO - [2025-02-07T00:15:40.169+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/gx.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gx.py", line 3, in <module>
    from great_expectations_provider.operators.great_expectations import (
  File "/home/airflow/.local/lib/python3.8/site-packages/great_expectations_provider/operators/great_expectations.py", line 30, in <module>
    from great_expectations.checkpoint.types.checkpoint_result import CheckpointResult
ModuleNotFoundError: No module named 'great_expectations.checkpoint.types'
[2025-02-07T00:15:40.170+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/gx.py
[2025-02-07T00:15:40.191+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/gx.py took 2.061 seconds
[2025-02-07T00:16:10.342+0000] {processor.py:157} INFO - Started process (PID=3860) to work on /opt/airflow/dags/gx.py
[2025-02-07T00:16:10.343+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/gx.py for tasks to queue
[2025-02-07T00:16:10.345+0000] {logging_mixin.py:151} INFO - [2025-02-07T00:16:10.345+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/gx.py
[2025-02-07T00:16:12.031+0000] {logging_mixin.py:151} INFO - [2025-02-07T00:16:12.031+0000] {warnings.py:109} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:103: UserWarning: You have an incompatible version of 'pyarrow' installed (11.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
  warn_incompatible_dep(
[2025-02-07T00:16:12.399+0000] {logging_mixin.py:151} INFO - [2025-02-07T00:16:12.398+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/gx.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gx.py", line 3, in <module>
    from great_expectations_provider.operators.great_expectations import (
  File "/home/airflow/.local/lib/python3.8/site-packages/great_expectations_provider/operators/great_expectations.py", line 30, in <module>
    from great_expectations.checkpoint.types.checkpoint_result import CheckpointResult
ModuleNotFoundError: No module named 'great_expectations.checkpoint.types'
[2025-02-07T00:16:12.400+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/gx.py
[2025-02-07T00:16:12.420+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/gx.py took 2.081 seconds
[2025-02-07T00:16:42.600+0000] {processor.py:157} INFO - Started process (PID=3881) to work on /opt/airflow/dags/gx.py
[2025-02-07T00:16:42.602+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/gx.py for tasks to queue
[2025-02-07T00:16:42.606+0000] {logging_mixin.py:151} INFO - [2025-02-07T00:16:42.606+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/gx.py
[2025-02-07T00:16:44.166+0000] {logging_mixin.py:151} INFO - [2025-02-07T00:16:44.166+0000] {warnings.py:109} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:103: UserWarning: You have an incompatible version of 'pyarrow' installed (11.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
  warn_incompatible_dep(
[2025-02-07T00:16:44.512+0000] {logging_mixin.py:151} INFO - [2025-02-07T00:16:44.511+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/gx.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gx.py", line 3, in <module>
    from great_expectations_provider.operators.great_expectations import (
  File "/home/airflow/.local/lib/python3.8/site-packages/great_expectations_provider/operators/great_expectations.py", line 30, in <module>
    from great_expectations.checkpoint.types.checkpoint_result import CheckpointResult
ModuleNotFoundError: No module named 'great_expectations.checkpoint.types'
[2025-02-07T00:16:44.513+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/gx.py
[2025-02-07T00:16:44.535+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/gx.py took 1.941 seconds
[2025-02-07T00:17:14.807+0000] {processor.py:157} INFO - Started process (PID=3902) to work on /opt/airflow/dags/gx.py
[2025-02-07T00:17:14.808+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/gx.py for tasks to queue
[2025-02-07T00:17:14.810+0000] {logging_mixin.py:151} INFO - [2025-02-07T00:17:14.810+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/gx.py
[2025-02-07T00:17:16.386+0000] {logging_mixin.py:151} INFO - [2025-02-07T00:17:16.386+0000] {warnings.py:109} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:103: UserWarning: You have an incompatible version of 'pyarrow' installed (11.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
  warn_incompatible_dep(
[2025-02-07T00:17:16.781+0000] {logging_mixin.py:151} INFO - [2025-02-07T00:17:16.780+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/gx.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gx.py", line 3, in <module>
    from great_expectations_provider.operators.great_expectations import (
  File "/home/airflow/.local/lib/python3.8/site-packages/great_expectations_provider/operators/great_expectations.py", line 30, in <module>
    from great_expectations.checkpoint.types.checkpoint_result import CheckpointResult
ModuleNotFoundError: No module named 'great_expectations.checkpoint.types'
[2025-02-07T00:17:16.782+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/gx.py
[2025-02-07T00:17:16.801+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/gx.py took 2.000 seconds
[2025-02-07T00:17:47.079+0000] {processor.py:157} INFO - Started process (PID=3923) to work on /opt/airflow/dags/gx.py
[2025-02-07T00:17:47.080+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/gx.py for tasks to queue
[2025-02-07T00:17:47.084+0000] {logging_mixin.py:151} INFO - [2025-02-07T00:17:47.083+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/gx.py
[2025-02-07T00:17:48.654+0000] {logging_mixin.py:151} INFO - [2025-02-07T00:17:48.654+0000] {warnings.py:109} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:103: UserWarning: You have an incompatible version of 'pyarrow' installed (11.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
  warn_incompatible_dep(
[2025-02-07T00:17:48.997+0000] {logging_mixin.py:151} INFO - [2025-02-07T00:17:48.996+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/gx.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gx.py", line 3, in <module>
    from great_expectations_provider.operators.great_expectations import (
  File "/home/airflow/.local/lib/python3.8/site-packages/great_expectations_provider/operators/great_expectations.py", line 30, in <module>
    from great_expectations.checkpoint.types.checkpoint_result import CheckpointResult
ModuleNotFoundError: No module named 'great_expectations.checkpoint.types'
[2025-02-07T00:17:48.998+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/gx.py
[2025-02-07T00:17:49.017+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/gx.py took 1.942 seconds
[2025-02-07T00:18:19.302+0000] {processor.py:157} INFO - Started process (PID=3944) to work on /opt/airflow/dags/gx.py
[2025-02-07T00:18:19.303+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/gx.py for tasks to queue
[2025-02-07T00:18:19.306+0000] {logging_mixin.py:151} INFO - [2025-02-07T00:18:19.306+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/gx.py
[2025-02-07T00:18:20.873+0000] {logging_mixin.py:151} INFO - [2025-02-07T00:18:20.873+0000] {warnings.py:109} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:103: UserWarning: You have an incompatible version of 'pyarrow' installed (11.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
  warn_incompatible_dep(
[2025-02-07T00:18:21.217+0000] {logging_mixin.py:151} INFO - [2025-02-07T00:18:21.216+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/gx.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gx.py", line 3, in <module>
    from great_expectations_provider.operators.great_expectations import (
  File "/home/airflow/.local/lib/python3.8/site-packages/great_expectations_provider/operators/great_expectations.py", line 30, in <module>
    from great_expectations.checkpoint.types.checkpoint_result import CheckpointResult
ModuleNotFoundError: No module named 'great_expectations.checkpoint.types'
[2025-02-07T00:18:21.218+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/gx.py
[2025-02-07T00:18:21.239+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/gx.py took 1.940 seconds
[2025-02-07T00:18:51.522+0000] {processor.py:157} INFO - Started process (PID=3965) to work on /opt/airflow/dags/gx.py
[2025-02-07T00:18:51.523+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/gx.py for tasks to queue
[2025-02-07T00:18:51.526+0000] {logging_mixin.py:151} INFO - [2025-02-07T00:18:51.525+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/gx.py
[2025-02-07T00:18:53.065+0000] {logging_mixin.py:151} INFO - [2025-02-07T00:18:53.065+0000] {warnings.py:109} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:103: UserWarning: You have an incompatible version of 'pyarrow' installed (11.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
  warn_incompatible_dep(
[2025-02-07T00:18:53.406+0000] {logging_mixin.py:151} INFO - [2025-02-07T00:18:53.405+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/gx.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gx.py", line 3, in <module>
    from great_expectations_provider.operators.great_expectations import (
  File "/home/airflow/.local/lib/python3.8/site-packages/great_expectations_provider/operators/great_expectations.py", line 30, in <module>
    from great_expectations.checkpoint.types.checkpoint_result import CheckpointResult
ModuleNotFoundError: No module named 'great_expectations.checkpoint.types'
[2025-02-07T00:18:53.406+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/gx.py
[2025-02-07T00:18:53.427+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/gx.py took 1.909 seconds
[2025-02-07T00:19:23.677+0000] {processor.py:157} INFO - Started process (PID=3985) to work on /opt/airflow/dags/gx.py
[2025-02-07T00:19:23.679+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/gx.py for tasks to queue
[2025-02-07T00:19:23.683+0000] {logging_mixin.py:151} INFO - [2025-02-07T00:19:23.683+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/gx.py
[2025-02-07T00:19:25.250+0000] {logging_mixin.py:151} INFO - [2025-02-07T00:19:25.250+0000] {warnings.py:109} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:103: UserWarning: You have an incompatible version of 'pyarrow' installed (11.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
  warn_incompatible_dep(
[2025-02-07T00:19:25.601+0000] {logging_mixin.py:151} INFO - [2025-02-07T00:19:25.600+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/gx.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gx.py", line 3, in <module>
    from great_expectations_provider.operators.great_expectations import (
  File "/home/airflow/.local/lib/python3.8/site-packages/great_expectations_provider/operators/great_expectations.py", line 30, in <module>
    from great_expectations.checkpoint.types.checkpoint_result import CheckpointResult
ModuleNotFoundError: No module named 'great_expectations.checkpoint.types'
[2025-02-07T00:19:25.601+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/gx.py
[2025-02-07T00:19:25.621+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/gx.py took 1.951 seconds
[2025-02-07T00:19:55.846+0000] {processor.py:157} INFO - Started process (PID=4013) to work on /opt/airflow/dags/gx.py
[2025-02-07T00:19:55.848+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/gx.py for tasks to queue
[2025-02-07T00:19:55.850+0000] {logging_mixin.py:151} INFO - [2025-02-07T00:19:55.850+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/gx.py
[2025-02-07T00:19:57.527+0000] {logging_mixin.py:151} INFO - [2025-02-07T00:19:57.527+0000] {warnings.py:109} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:103: UserWarning: You have an incompatible version of 'pyarrow' installed (11.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
  warn_incompatible_dep(
[2025-02-07T00:19:57.900+0000] {logging_mixin.py:151} INFO - [2025-02-07T00:19:57.899+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/gx.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gx.py", line 3, in <module>
    from great_expectations_provider.operators.great_expectations import (
  File "/home/airflow/.local/lib/python3.8/site-packages/great_expectations_provider/operators/great_expectations.py", line 30, in <module>
    from great_expectations.checkpoint.types.checkpoint_result import CheckpointResult
ModuleNotFoundError: No module named 'great_expectations.checkpoint.types'
[2025-02-07T00:19:57.900+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/gx.py
[2025-02-07T00:19:57.920+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/gx.py took 2.081 seconds
[2025-02-07T00:20:28.064+0000] {processor.py:157} INFO - Started process (PID=4034) to work on /opt/airflow/dags/gx.py
[2025-02-07T00:20:28.065+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/gx.py for tasks to queue
[2025-02-07T00:20:28.067+0000] {logging_mixin.py:151} INFO - [2025-02-07T00:20:28.067+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/gx.py
[2025-02-07T00:20:29.775+0000] {logging_mixin.py:151} INFO - [2025-02-07T00:20:29.774+0000] {warnings.py:109} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:103: UserWarning: You have an incompatible version of 'pyarrow' installed (11.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
  warn_incompatible_dep(
[2025-02-07T00:20:30.132+0000] {logging_mixin.py:151} INFO - [2025-02-07T00:20:30.131+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/gx.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gx.py", line 3, in <module>
    from great_expectations_provider.operators.great_expectations import (
  File "/home/airflow/.local/lib/python3.8/site-packages/great_expectations_provider/operators/great_expectations.py", line 30, in <module>
    from great_expectations.checkpoint.types.checkpoint_result import CheckpointResult
ModuleNotFoundError: No module named 'great_expectations.checkpoint.types'
[2025-02-07T00:20:30.133+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/gx.py
[2025-02-07T00:20:30.153+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/gx.py took 2.092 seconds
[2025-02-07T00:21:00.336+0000] {processor.py:157} INFO - Started process (PID=4055) to work on /opt/airflow/dags/gx.py
[2025-02-07T00:21:00.337+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/gx.py for tasks to queue
[2025-02-07T00:21:00.340+0000] {logging_mixin.py:151} INFO - [2025-02-07T00:21:00.339+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/gx.py
[2025-02-07T00:21:02.059+0000] {logging_mixin.py:151} INFO - [2025-02-07T00:21:02.058+0000] {warnings.py:109} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:103: UserWarning: You have an incompatible version of 'pyarrow' installed (11.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
  warn_incompatible_dep(
[2025-02-07T00:21:02.413+0000] {logging_mixin.py:151} INFO - [2025-02-07T00:21:02.412+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/gx.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gx.py", line 3, in <module>
    from great_expectations_provider.operators.great_expectations import (
  File "/home/airflow/.local/lib/python3.8/site-packages/great_expectations_provider/operators/great_expectations.py", line 30, in <module>
    from great_expectations.checkpoint.types.checkpoint_result import CheckpointResult
ModuleNotFoundError: No module named 'great_expectations.checkpoint.types'
[2025-02-07T00:21:02.413+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/gx.py
[2025-02-07T00:21:02.433+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/gx.py took 2.101 seconds
[2025-02-07T00:21:32.590+0000] {processor.py:157} INFO - Started process (PID=4076) to work on /opt/airflow/dags/gx.py
[2025-02-07T00:21:32.592+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/gx.py for tasks to queue
[2025-02-07T00:21:32.595+0000] {logging_mixin.py:151} INFO - [2025-02-07T00:21:32.595+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/gx.py
[2025-02-07T00:21:34.184+0000] {logging_mixin.py:151} INFO - [2025-02-07T00:21:34.183+0000] {warnings.py:109} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:103: UserWarning: You have an incompatible version of 'pyarrow' installed (11.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
  warn_incompatible_dep(
[2025-02-07T00:21:34.538+0000] {logging_mixin.py:151} INFO - [2025-02-07T00:21:34.537+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/gx.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gx.py", line 3, in <module>
    from great_expectations_provider.operators.great_expectations import (
  File "/home/airflow/.local/lib/python3.8/site-packages/great_expectations_provider/operators/great_expectations.py", line 30, in <module>
    from great_expectations.checkpoint.types.checkpoint_result import CheckpointResult
ModuleNotFoundError: No module named 'great_expectations.checkpoint.types'
[2025-02-07T00:21:34.539+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/gx.py
[2025-02-07T00:21:34.563+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/gx.py took 1.980 seconds
[2025-02-07T00:22:04.825+0000] {processor.py:157} INFO - Started process (PID=4097) to work on /opt/airflow/dags/gx.py
[2025-02-07T00:22:04.826+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/gx.py for tasks to queue
[2025-02-07T00:22:04.828+0000] {logging_mixin.py:151} INFO - [2025-02-07T00:22:04.828+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/gx.py
[2025-02-07T00:22:06.645+0000] {logging_mixin.py:151} INFO - [2025-02-07T00:22:06.644+0000] {warnings.py:109} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:103: UserWarning: You have an incompatible version of 'pyarrow' installed (11.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
  warn_incompatible_dep(
[2025-02-07T00:22:07.017+0000] {logging_mixin.py:151} INFO - [2025-02-07T00:22:07.016+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/gx.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gx.py", line 3, in <module>
    from great_expectations_provider.operators.great_expectations import (
  File "/home/airflow/.local/lib/python3.8/site-packages/great_expectations_provider/operators/great_expectations.py", line 30, in <module>
    from great_expectations.checkpoint.types.checkpoint_result import CheckpointResult
ModuleNotFoundError: No module named 'great_expectations.checkpoint.types'
[2025-02-07T00:22:07.018+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/gx.py
[2025-02-07T00:22:07.038+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/gx.py took 2.216 seconds
[2025-02-07T00:22:37.261+0000] {processor.py:157} INFO - Started process (PID=4118) to work on /opt/airflow/dags/gx.py
[2025-02-07T00:22:37.262+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/gx.py for tasks to queue
[2025-02-07T00:22:37.264+0000] {logging_mixin.py:151} INFO - [2025-02-07T00:22:37.263+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/gx.py
[2025-02-07T00:22:39.012+0000] {logging_mixin.py:151} INFO - [2025-02-07T00:22:39.011+0000] {warnings.py:109} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:103: UserWarning: You have an incompatible version of 'pyarrow' installed (11.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
  warn_incompatible_dep(
[2025-02-07T00:22:39.399+0000] {logging_mixin.py:151} INFO - [2025-02-07T00:22:39.398+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/gx.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gx.py", line 3, in <module>
    from great_expectations_provider.operators.great_expectations import (
  File "/home/airflow/.local/lib/python3.8/site-packages/great_expectations_provider/operators/great_expectations.py", line 30, in <module>
    from great_expectations.checkpoint.types.checkpoint_result import CheckpointResult
ModuleNotFoundError: No module named 'great_expectations.checkpoint.types'
[2025-02-07T00:22:39.400+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/gx.py
[2025-02-07T00:22:39.423+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/gx.py took 2.165 seconds
[2025-02-07T00:23:09.514+0000] {processor.py:157} INFO - Started process (PID=4139) to work on /opt/airflow/dags/gx.py
[2025-02-07T00:23:09.515+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/gx.py for tasks to queue
[2025-02-07T00:23:09.518+0000] {logging_mixin.py:151} INFO - [2025-02-07T00:23:09.517+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/gx.py
[2025-02-07T00:23:11.246+0000] {logging_mixin.py:151} INFO - [2025-02-07T00:23:11.246+0000] {warnings.py:109} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:103: UserWarning: You have an incompatible version of 'pyarrow' installed (11.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
  warn_incompatible_dep(
[2025-02-07T00:23:11.678+0000] {logging_mixin.py:151} INFO - [2025-02-07T00:23:11.677+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/gx.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gx.py", line 3, in <module>
    from great_expectations_provider.operators.great_expectations import (
  File "/home/airflow/.local/lib/python3.8/site-packages/great_expectations_provider/operators/great_expectations.py", line 30, in <module>
    from great_expectations.checkpoint.types.checkpoint_result import CheckpointResult
ModuleNotFoundError: No module named 'great_expectations.checkpoint.types'
[2025-02-07T00:23:11.678+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/gx.py
[2025-02-07T00:23:11.701+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/gx.py took 2.190 seconds
[2025-02-07T00:23:41.851+0000] {processor.py:157} INFO - Started process (PID=4160) to work on /opt/airflow/dags/gx.py
[2025-02-07T00:23:41.852+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/gx.py for tasks to queue
[2025-02-07T00:23:41.855+0000] {logging_mixin.py:151} INFO - [2025-02-07T00:23:41.855+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/gx.py
[2025-02-07T00:23:43.714+0000] {logging_mixin.py:151} INFO - [2025-02-07T00:23:43.713+0000] {warnings.py:109} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:103: UserWarning: You have an incompatible version of 'pyarrow' installed (11.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
  warn_incompatible_dep(
[2025-02-07T00:23:44.107+0000] {logging_mixin.py:151} INFO - [2025-02-07T00:23:44.106+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/gx.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gx.py", line 3, in <module>
    from great_expectations_provider.operators.great_expectations import (
  File "/home/airflow/.local/lib/python3.8/site-packages/great_expectations_provider/operators/great_expectations.py", line 30, in <module>
    from great_expectations.checkpoint.types.checkpoint_result import CheckpointResult
ModuleNotFoundError: No module named 'great_expectations.checkpoint.types'
[2025-02-07T00:23:44.107+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/gx.py
[2025-02-07T00:23:44.120+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/gx.py took 2.277 seconds
[2025-02-07T00:24:14.330+0000] {processor.py:157} INFO - Started process (PID=4181) to work on /opt/airflow/dags/gx.py
[2025-02-07T00:24:14.331+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/gx.py for tasks to queue
[2025-02-07T00:24:14.333+0000] {logging_mixin.py:151} INFO - [2025-02-07T00:24:14.333+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/gx.py
[2025-02-07T00:24:16.090+0000] {logging_mixin.py:151} INFO - [2025-02-07T00:24:16.090+0000] {warnings.py:109} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:103: UserWarning: You have an incompatible version of 'pyarrow' installed (11.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
  warn_incompatible_dep(
[2025-02-07T00:24:16.453+0000] {logging_mixin.py:151} INFO - [2025-02-07T00:24:16.452+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/gx.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gx.py", line 3, in <module>
    from great_expectations_provider.operators.great_expectations import (
  File "/home/airflow/.local/lib/python3.8/site-packages/great_expectations_provider/operators/great_expectations.py", line 30, in <module>
    from great_expectations.checkpoint.types.checkpoint_result import CheckpointResult
ModuleNotFoundError: No module named 'great_expectations.checkpoint.types'
[2025-02-07T00:24:16.454+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/gx.py
[2025-02-07T00:24:16.474+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/gx.py took 2.147 seconds
[2025-02-07T00:24:46.555+0000] {processor.py:157} INFO - Started process (PID=4202) to work on /opt/airflow/dags/gx.py
[2025-02-07T00:24:46.557+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/gx.py for tasks to queue
[2025-02-07T00:24:46.560+0000] {logging_mixin.py:151} INFO - [2025-02-07T00:24:46.560+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/gx.py
[2025-02-07T00:24:48.122+0000] {logging_mixin.py:151} INFO - [2025-02-07T00:24:48.122+0000] {warnings.py:109} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:103: UserWarning: You have an incompatible version of 'pyarrow' installed (11.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
  warn_incompatible_dep(
[2025-02-07T00:24:48.466+0000] {logging_mixin.py:151} INFO - [2025-02-07T00:24:48.465+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/gx.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gx.py", line 3, in <module>
    from great_expectations_provider.operators.great_expectations import (
  File "/home/airflow/.local/lib/python3.8/site-packages/great_expectations_provider/operators/great_expectations.py", line 30, in <module>
    from great_expectations.checkpoint.types.checkpoint_result import CheckpointResult
ModuleNotFoundError: No module named 'great_expectations.checkpoint.types'
[2025-02-07T00:24:48.467+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/gx.py
[2025-02-07T00:24:48.480+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/gx.py took 1.931 seconds
[2025-02-07T00:25:18.770+0000] {processor.py:157} INFO - Started process (PID=4223) to work on /opt/airflow/dags/gx.py
[2025-02-07T00:25:18.772+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/gx.py for tasks to queue
[2025-02-07T00:25:18.775+0000] {logging_mixin.py:151} INFO - [2025-02-07T00:25:18.775+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/gx.py
[2025-02-07T00:25:20.373+0000] {logging_mixin.py:151} INFO - [2025-02-07T00:25:20.372+0000] {warnings.py:109} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:103: UserWarning: You have an incompatible version of 'pyarrow' installed (11.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
  warn_incompatible_dep(
[2025-02-07T00:25:20.718+0000] {logging_mixin.py:151} INFO - [2025-02-07T00:25:20.717+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/gx.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gx.py", line 3, in <module>
    from great_expectations_provider.operators.great_expectations import (
  File "/home/airflow/.local/lib/python3.8/site-packages/great_expectations_provider/operators/great_expectations.py", line 30, in <module>
    from great_expectations.checkpoint.types.checkpoint_result import CheckpointResult
ModuleNotFoundError: No module named 'great_expectations.checkpoint.types'
[2025-02-07T00:25:20.719+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/gx.py
[2025-02-07T00:25:20.731+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/gx.py took 1.968 seconds
[2025-02-07T00:25:50.984+0000] {processor.py:157} INFO - Started process (PID=4244) to work on /opt/airflow/dags/gx.py
[2025-02-07T00:25:50.985+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/gx.py for tasks to queue
[2025-02-07T00:25:50.988+0000] {logging_mixin.py:151} INFO - [2025-02-07T00:25:50.987+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/gx.py
[2025-02-07T00:25:52.596+0000] {logging_mixin.py:151} INFO - [2025-02-07T00:25:52.595+0000] {warnings.py:109} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:103: UserWarning: You have an incompatible version of 'pyarrow' installed (11.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
  warn_incompatible_dep(
[2025-02-07T00:25:52.941+0000] {logging_mixin.py:151} INFO - [2025-02-07T00:25:52.939+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/gx.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gx.py", line 3, in <module>
    from great_expectations_provider.operators.great_expectations import (
  File "/home/airflow/.local/lib/python3.8/site-packages/great_expectations_provider/operators/great_expectations.py", line 30, in <module>
    from great_expectations.checkpoint.types.checkpoint_result import CheckpointResult
ModuleNotFoundError: No module named 'great_expectations.checkpoint.types'
[2025-02-07T00:25:52.941+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/gx.py
[2025-02-07T00:25:52.955+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/gx.py took 1.974 seconds
[2025-02-07T00:26:23.175+0000] {processor.py:157} INFO - Started process (PID=4265) to work on /opt/airflow/dags/gx.py
[2025-02-07T00:26:23.176+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/gx.py for tasks to queue
[2025-02-07T00:26:23.178+0000] {logging_mixin.py:151} INFO - [2025-02-07T00:26:23.178+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/gx.py
[2025-02-07T00:26:25.029+0000] {logging_mixin.py:151} INFO - [2025-02-07T00:26:25.028+0000] {warnings.py:109} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:103: UserWarning: You have an incompatible version of 'pyarrow' installed (11.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
  warn_incompatible_dep(
[2025-02-07T00:26:25.386+0000] {logging_mixin.py:151} INFO - [2025-02-07T00:26:25.385+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/gx.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gx.py", line 3, in <module>
    from great_expectations_provider.operators.great_expectations import (
  File "/home/airflow/.local/lib/python3.8/site-packages/great_expectations_provider/operators/great_expectations.py", line 30, in <module>
    from great_expectations.checkpoint.types.checkpoint_result import CheckpointResult
ModuleNotFoundError: No module named 'great_expectations.checkpoint.types'
[2025-02-07T00:26:25.386+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/gx.py
[2025-02-07T00:26:25.407+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/gx.py took 2.235 seconds
[2025-02-07T00:26:55.469+0000] {processor.py:157} INFO - Started process (PID=4286) to work on /opt/airflow/dags/gx.py
[2025-02-07T00:26:55.470+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/gx.py for tasks to queue
[2025-02-07T00:26:55.473+0000] {logging_mixin.py:151} INFO - [2025-02-07T00:26:55.472+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/gx.py
[2025-02-07T00:26:57.144+0000] {logging_mixin.py:151} INFO - [2025-02-07T00:26:57.144+0000] {warnings.py:109} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:103: UserWarning: You have an incompatible version of 'pyarrow' installed (11.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
  warn_incompatible_dep(
[2025-02-07T00:26:57.489+0000] {logging_mixin.py:151} INFO - [2025-02-07T00:26:57.488+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/gx.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gx.py", line 3, in <module>
    from great_expectations_provider.operators.great_expectations import (
  File "/home/airflow/.local/lib/python3.8/site-packages/great_expectations_provider/operators/great_expectations.py", line 30, in <module>
    from great_expectations.checkpoint.types.checkpoint_result import CheckpointResult
ModuleNotFoundError: No module named 'great_expectations.checkpoint.types'
[2025-02-07T00:26:57.489+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/gx.py
[2025-02-07T00:26:57.502+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/gx.py took 2.035 seconds
[2025-02-07T00:27:27.712+0000] {processor.py:157} INFO - Started process (PID=4314) to work on /opt/airflow/dags/gx.py
[2025-02-07T00:27:27.713+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/gx.py for tasks to queue
[2025-02-07T00:27:27.716+0000] {logging_mixin.py:151} INFO - [2025-02-07T00:27:27.716+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/gx.py
[2025-02-07T00:27:29.336+0000] {logging_mixin.py:151} INFO - [2025-02-07T00:27:29.335+0000] {warnings.py:109} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:103: UserWarning: You have an incompatible version of 'pyarrow' installed (11.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
  warn_incompatible_dep(
[2025-02-07T00:27:29.702+0000] {logging_mixin.py:151} INFO - [2025-02-07T00:27:29.701+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/gx.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gx.py", line 3, in <module>
    from great_expectations_provider.operators.great_expectations import (
  File "/home/airflow/.local/lib/python3.8/site-packages/great_expectations_provider/operators/great_expectations.py", line 30, in <module>
    from great_expectations.checkpoint.types.checkpoint_result import CheckpointResult
ModuleNotFoundError: No module named 'great_expectations.checkpoint.types'
[2025-02-07T00:27:29.703+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/gx.py
[2025-02-07T00:27:29.716+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/gx.py took 2.006 seconds
[2025-02-07T00:27:59.942+0000] {processor.py:157} INFO - Started process (PID=4335) to work on /opt/airflow/dags/gx.py
[2025-02-07T00:27:59.944+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/gx.py for tasks to queue
[2025-02-07T00:27:59.946+0000] {logging_mixin.py:151} INFO - [2025-02-07T00:27:59.946+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/gx.py
[2025-02-07T00:28:01.541+0000] {logging_mixin.py:151} INFO - [2025-02-07T00:28:01.540+0000] {warnings.py:109} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:103: UserWarning: You have an incompatible version of 'pyarrow' installed (11.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
  warn_incompatible_dep(
[2025-02-07T00:28:01.891+0000] {logging_mixin.py:151} INFO - [2025-02-07T00:28:01.890+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/gx.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gx.py", line 3, in <module>
    from great_expectations_provider.operators.great_expectations import (
  File "/home/airflow/.local/lib/python3.8/site-packages/great_expectations_provider/operators/great_expectations.py", line 30, in <module>
    from great_expectations.checkpoint.types.checkpoint_result import CheckpointResult
ModuleNotFoundError: No module named 'great_expectations.checkpoint.types'
[2025-02-07T00:28:01.892+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/gx.py
[2025-02-07T00:28:01.913+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/gx.py took 1.973 seconds
[2025-02-07T00:28:32.197+0000] {processor.py:157} INFO - Started process (PID=4356) to work on /opt/airflow/dags/gx.py
[2025-02-07T00:28:32.198+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/gx.py for tasks to queue
[2025-02-07T00:28:32.200+0000] {logging_mixin.py:151} INFO - [2025-02-07T00:28:32.200+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/gx.py
[2025-02-07T00:28:33.802+0000] {logging_mixin.py:151} INFO - [2025-02-07T00:28:33.802+0000] {warnings.py:109} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:103: UserWarning: You have an incompatible version of 'pyarrow' installed (11.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
  warn_incompatible_dep(
[2025-02-07T00:28:34.148+0000] {logging_mixin.py:151} INFO - [2025-02-07T00:28:34.147+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/gx.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gx.py", line 3, in <module>
    from great_expectations_provider.operators.great_expectations import (
  File "/home/airflow/.local/lib/python3.8/site-packages/great_expectations_provider/operators/great_expectations.py", line 30, in <module>
    from great_expectations.checkpoint.types.checkpoint_result import CheckpointResult
ModuleNotFoundError: No module named 'great_expectations.checkpoint.types'
[2025-02-07T00:28:34.149+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/gx.py
[2025-02-07T00:28:34.170+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/gx.py took 1.975 seconds
[2025-02-07T00:29:04.450+0000] {processor.py:157} INFO - Started process (PID=4377) to work on /opt/airflow/dags/gx.py
[2025-02-07T00:29:04.451+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/gx.py for tasks to queue
[2025-02-07T00:29:04.453+0000] {logging_mixin.py:151} INFO - [2025-02-07T00:29:04.453+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/gx.py
[2025-02-07T00:29:06.047+0000] {logging_mixin.py:151} INFO - [2025-02-07T00:29:06.047+0000] {warnings.py:109} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:103: UserWarning: You have an incompatible version of 'pyarrow' installed (11.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
  warn_incompatible_dep(
[2025-02-07T00:29:06.398+0000] {logging_mixin.py:151} INFO - [2025-02-07T00:29:06.397+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/gx.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gx.py", line 3, in <module>
    from great_expectations_provider.operators.great_expectations import (
  File "/home/airflow/.local/lib/python3.8/site-packages/great_expectations_provider/operators/great_expectations.py", line 30, in <module>
    from great_expectations.checkpoint.types.checkpoint_result import CheckpointResult
ModuleNotFoundError: No module named 'great_expectations.checkpoint.types'
[2025-02-07T00:29:06.399+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/gx.py
[2025-02-07T00:29:06.420+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/gx.py took 1.974 seconds
[2025-02-07T00:29:36.696+0000] {processor.py:157} INFO - Started process (PID=4398) to work on /opt/airflow/dags/gx.py
[2025-02-07T00:29:36.698+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/gx.py for tasks to queue
[2025-02-07T00:29:36.700+0000] {logging_mixin.py:151} INFO - [2025-02-07T00:29:36.700+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/gx.py
[2025-02-07T00:29:38.303+0000] {logging_mixin.py:151} INFO - [2025-02-07T00:29:38.303+0000] {warnings.py:109} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:103: UserWarning: You have an incompatible version of 'pyarrow' installed (11.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
  warn_incompatible_dep(
[2025-02-07T00:29:38.659+0000] {logging_mixin.py:151} INFO - [2025-02-07T00:29:38.658+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/gx.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gx.py", line 3, in <module>
    from great_expectations_provider.operators.great_expectations import (
  File "/home/airflow/.local/lib/python3.8/site-packages/great_expectations_provider/operators/great_expectations.py", line 30, in <module>
    from great_expectations.checkpoint.types.checkpoint_result import CheckpointResult
ModuleNotFoundError: No module named 'great_expectations.checkpoint.types'
[2025-02-07T00:29:38.659+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/gx.py
[2025-02-07T00:29:38.680+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/gx.py took 1.987 seconds
[2025-02-07T00:30:08.951+0000] {processor.py:157} INFO - Started process (PID=4419) to work on /opt/airflow/dags/gx.py
[2025-02-07T00:30:08.952+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/gx.py for tasks to queue
[2025-02-07T00:30:08.954+0000] {logging_mixin.py:151} INFO - [2025-02-07T00:30:08.954+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/gx.py
[2025-02-07T00:30:10.565+0000] {logging_mixin.py:151} INFO - [2025-02-07T00:30:10.565+0000] {warnings.py:109} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:103: UserWarning: You have an incompatible version of 'pyarrow' installed (11.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
  warn_incompatible_dep(
[2025-02-07T00:30:10.915+0000] {logging_mixin.py:151} INFO - [2025-02-07T00:30:10.914+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/gx.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gx.py", line 3, in <module>
    from great_expectations_provider.operators.great_expectations import (
  File "/home/airflow/.local/lib/python3.8/site-packages/great_expectations_provider/operators/great_expectations.py", line 30, in <module>
    from great_expectations.checkpoint.types.checkpoint_result import CheckpointResult
ModuleNotFoundError: No module named 'great_expectations.checkpoint.types'
[2025-02-07T00:30:10.915+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/gx.py
[2025-02-07T00:30:10.936+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/gx.py took 1.989 seconds
[2025-02-07T00:30:41.213+0000] {processor.py:157} INFO - Started process (PID=4440) to work on /opt/airflow/dags/gx.py
[2025-02-07T00:30:41.214+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/gx.py for tasks to queue
[2025-02-07T00:30:41.216+0000] {logging_mixin.py:151} INFO - [2025-02-07T00:30:41.216+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/gx.py
[2025-02-07T00:30:42.803+0000] {logging_mixin.py:151} INFO - [2025-02-07T00:30:42.802+0000] {warnings.py:109} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:103: UserWarning: You have an incompatible version of 'pyarrow' installed (11.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
  warn_incompatible_dep(
[2025-02-07T00:30:43.150+0000] {logging_mixin.py:151} INFO - [2025-02-07T00:30:43.148+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/gx.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gx.py", line 3, in <module>
    from great_expectations_provider.operators.great_expectations import (
  File "/home/airflow/.local/lib/python3.8/site-packages/great_expectations_provider/operators/great_expectations.py", line 30, in <module>
    from great_expectations.checkpoint.types.checkpoint_result import CheckpointResult
ModuleNotFoundError: No module named 'great_expectations.checkpoint.types'
[2025-02-07T00:30:43.150+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/gx.py
[2025-02-07T00:30:43.171+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/gx.py took 1.962 seconds
[2025-02-07T00:31:13.457+0000] {processor.py:157} INFO - Started process (PID=4461) to work on /opt/airflow/dags/gx.py
[2025-02-07T00:31:13.458+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/gx.py for tasks to queue
[2025-02-07T00:31:13.460+0000] {logging_mixin.py:151} INFO - [2025-02-07T00:31:13.460+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/gx.py
[2025-02-07T00:31:15.052+0000] {logging_mixin.py:151} INFO - [2025-02-07T00:31:15.052+0000] {warnings.py:109} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:103: UserWarning: You have an incompatible version of 'pyarrow' installed (11.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
  warn_incompatible_dep(
[2025-02-07T00:31:15.402+0000] {logging_mixin.py:151} INFO - [2025-02-07T00:31:15.401+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/gx.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gx.py", line 3, in <module>
    from great_expectations_provider.operators.great_expectations import (
  File "/home/airflow/.local/lib/python3.8/site-packages/great_expectations_provider/operators/great_expectations.py", line 30, in <module>
    from great_expectations.checkpoint.types.checkpoint_result import CheckpointResult
ModuleNotFoundError: No module named 'great_expectations.checkpoint.types'
[2025-02-07T00:31:15.402+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/gx.py
[2025-02-07T00:31:15.415+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/gx.py took 1.961 seconds
[2025-02-07T00:31:45.660+0000] {processor.py:157} INFO - Started process (PID=4482) to work on /opt/airflow/dags/gx.py
[2025-02-07T00:31:45.661+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/gx.py for tasks to queue
[2025-02-07T00:31:45.664+0000] {logging_mixin.py:151} INFO - [2025-02-07T00:31:45.663+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/gx.py
[2025-02-07T00:31:47.348+0000] {logging_mixin.py:151} INFO - [2025-02-07T00:31:47.347+0000] {warnings.py:109} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:103: UserWarning: You have an incompatible version of 'pyarrow' installed (11.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
  warn_incompatible_dep(
[2025-02-07T00:31:47.693+0000] {logging_mixin.py:151} INFO - [2025-02-07T00:31:47.692+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/gx.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gx.py", line 3, in <module>
    from great_expectations_provider.operators.great_expectations import (
  File "/home/airflow/.local/lib/python3.8/site-packages/great_expectations_provider/operators/great_expectations.py", line 30, in <module>
    from great_expectations.checkpoint.types.checkpoint_result import CheckpointResult
ModuleNotFoundError: No module named 'great_expectations.checkpoint.types'
[2025-02-07T00:31:47.694+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/gx.py
[2025-02-07T00:31:47.714+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/gx.py took 2.057 seconds
[2025-02-07T00:32:17.867+0000] {processor.py:157} INFO - Started process (PID=4503) to work on /opt/airflow/dags/gx.py
[2025-02-07T00:32:17.868+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/gx.py for tasks to queue
[2025-02-07T00:32:17.871+0000] {logging_mixin.py:151} INFO - [2025-02-07T00:32:17.870+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/gx.py
[2025-02-07T00:32:19.677+0000] {logging_mixin.py:151} INFO - [2025-02-07T00:32:19.677+0000] {warnings.py:109} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:103: UserWarning: You have an incompatible version of 'pyarrow' installed (11.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
  warn_incompatible_dep(
[2025-02-07T00:32:20.044+0000] {logging_mixin.py:151} INFO - [2025-02-07T00:32:20.042+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/gx.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gx.py", line 3, in <module>
    from great_expectations_provider.operators.great_expectations import (
  File "/home/airflow/.local/lib/python3.8/site-packages/great_expectations_provider/operators/great_expectations.py", line 30, in <module>
    from great_expectations.checkpoint.types.checkpoint_result import CheckpointResult
ModuleNotFoundError: No module named 'great_expectations.checkpoint.types'
[2025-02-07T00:32:20.044+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/gx.py
[2025-02-07T00:32:20.068+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/gx.py took 2.204 seconds
[2025-02-07T00:32:50.108+0000] {processor.py:157} INFO - Started process (PID=4524) to work on /opt/airflow/dags/gx.py
[2025-02-07T00:32:50.109+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/gx.py for tasks to queue
[2025-02-07T00:32:50.112+0000] {logging_mixin.py:151} INFO - [2025-02-07T00:32:50.111+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/gx.py
[2025-02-07T00:32:51.982+0000] {logging_mixin.py:151} INFO - [2025-02-07T00:32:51.981+0000] {warnings.py:109} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:103: UserWarning: You have an incompatible version of 'pyarrow' installed (11.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
  warn_incompatible_dep(
[2025-02-07T00:32:52.387+0000] {logging_mixin.py:151} INFO - [2025-02-07T00:32:52.386+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/gx.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gx.py", line 3, in <module>
    from great_expectations_provider.operators.great_expectations import (
  File "/home/airflow/.local/lib/python3.8/site-packages/great_expectations_provider/operators/great_expectations.py", line 30, in <module>
    from great_expectations.checkpoint.types.checkpoint_result import CheckpointResult
ModuleNotFoundError: No module named 'great_expectations.checkpoint.types'
[2025-02-07T00:32:52.388+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/gx.py
[2025-02-07T00:32:52.400+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/gx.py took 2.295 seconds
[2025-02-07T00:33:22.428+0000] {processor.py:157} INFO - Started process (PID=4545) to work on /opt/airflow/dags/gx.py
[2025-02-07T00:33:22.429+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/gx.py for tasks to queue
[2025-02-07T00:33:22.431+0000] {logging_mixin.py:151} INFO - [2025-02-07T00:33:22.431+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/gx.py
[2025-02-07T00:33:24.101+0000] {logging_mixin.py:151} INFO - [2025-02-07T00:33:24.100+0000] {warnings.py:109} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:103: UserWarning: You have an incompatible version of 'pyarrow' installed (11.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
  warn_incompatible_dep(
[2025-02-07T00:33:24.521+0000] {logging_mixin.py:151} INFO - [2025-02-07T00:33:24.520+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/gx.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gx.py", line 3, in <module>
    from great_expectations_provider.operators.great_expectations import (
  File "/home/airflow/.local/lib/python3.8/site-packages/great_expectations_provider/operators/great_expectations.py", line 30, in <module>
    from great_expectations.checkpoint.types.checkpoint_result import CheckpointResult
ModuleNotFoundError: No module named 'great_expectations.checkpoint.types'
[2025-02-07T00:33:24.521+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/gx.py
[2025-02-07T00:33:24.533+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/gx.py took 2.108 seconds
[2025-02-07T00:33:54.585+0000] {processor.py:157} INFO - Started process (PID=4566) to work on /opt/airflow/dags/gx.py
[2025-02-07T00:33:54.586+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/gx.py for tasks to queue
[2025-02-07T00:33:54.588+0000] {logging_mixin.py:151} INFO - [2025-02-07T00:33:54.588+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/gx.py
[2025-02-07T00:33:56.474+0000] {logging_mixin.py:151} INFO - [2025-02-07T00:33:56.473+0000] {warnings.py:109} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:103: UserWarning: You have an incompatible version of 'pyarrow' installed (11.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
  warn_incompatible_dep(
[2025-02-07T00:33:56.893+0000] {logging_mixin.py:151} INFO - [2025-02-07T00:33:56.892+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/gx.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gx.py", line 3, in <module>
    from great_expectations_provider.operators.great_expectations import (
  File "/home/airflow/.local/lib/python3.8/site-packages/great_expectations_provider/operators/great_expectations.py", line 30, in <module>
    from great_expectations.checkpoint.types.checkpoint_result import CheckpointResult
ModuleNotFoundError: No module named 'great_expectations.checkpoint.types'
[2025-02-07T00:33:56.894+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/gx.py
[2025-02-07T00:33:56.906+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/gx.py took 2.325 seconds
[2025-02-07T00:34:27.059+0000] {processor.py:157} INFO - Started process (PID=4594) to work on /opt/airflow/dags/gx.py
[2025-02-07T00:34:27.060+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/gx.py for tasks to queue
[2025-02-07T00:34:27.063+0000] {logging_mixin.py:151} INFO - [2025-02-07T00:34:27.062+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/gx.py
[2025-02-07T00:34:28.958+0000] {logging_mixin.py:151} INFO - [2025-02-07T00:34:28.958+0000] {warnings.py:109} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:103: UserWarning: You have an incompatible version of 'pyarrow' installed (11.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
  warn_incompatible_dep(
[2025-02-07T00:34:29.396+0000] {logging_mixin.py:151} INFO - [2025-02-07T00:34:29.394+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/gx.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gx.py", line 3, in <module>
    from great_expectations_provider.operators.great_expectations import (
  File "/home/airflow/.local/lib/python3.8/site-packages/great_expectations_provider/operators/great_expectations.py", line 30, in <module>
    from great_expectations.checkpoint.types.checkpoint_result import CheckpointResult
ModuleNotFoundError: No module named 'great_expectations.checkpoint.types'
[2025-02-07T00:34:29.397+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/gx.py
[2025-02-07T00:34:29.413+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/gx.py took 2.358 seconds
[2025-02-07T00:34:59.633+0000] {processor.py:157} INFO - Started process (PID=4615) to work on /opt/airflow/dags/gx.py
[2025-02-07T00:34:59.634+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/gx.py for tasks to queue
[2025-02-07T00:34:59.639+0000] {logging_mixin.py:151} INFO - [2025-02-07T00:34:59.638+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/gx.py
[2025-02-07T00:35:01.348+0000] {logging_mixin.py:151} INFO - [2025-02-07T00:35:01.347+0000] {warnings.py:109} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:103: UserWarning: You have an incompatible version of 'pyarrow' installed (11.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
  warn_incompatible_dep(
[2025-02-07T00:35:01.722+0000] {logging_mixin.py:151} INFO - [2025-02-07T00:35:01.720+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/gx.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gx.py", line 3, in <module>
    from great_expectations_provider.operators.great_expectations import (
  File "/home/airflow/.local/lib/python3.8/site-packages/great_expectations_provider/operators/great_expectations.py", line 30, in <module>
    from great_expectations.checkpoint.types.checkpoint_result import CheckpointResult
ModuleNotFoundError: No module named 'great_expectations.checkpoint.types'
[2025-02-07T00:35:01.722+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/gx.py
[2025-02-07T00:35:01.737+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/gx.py took 2.112 seconds
[2025-02-07T00:35:31.858+0000] {processor.py:157} INFO - Started process (PID=4636) to work on /opt/airflow/dags/gx.py
[2025-02-07T00:35:31.860+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/gx.py for tasks to queue
[2025-02-07T00:35:31.864+0000] {logging_mixin.py:151} INFO - [2025-02-07T00:35:31.863+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/gx.py
[2025-02-07T00:35:33.536+0000] {logging_mixin.py:151} INFO - [2025-02-07T00:35:33.536+0000] {warnings.py:109} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:103: UserWarning: You have an incompatible version of 'pyarrow' installed (11.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
  warn_incompatible_dep(
[2025-02-07T00:35:33.895+0000] {logging_mixin.py:151} INFO - [2025-02-07T00:35:33.894+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/gx.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gx.py", line 3, in <module>
    from great_expectations_provider.operators.great_expectations import (
  File "/home/airflow/.local/lib/python3.8/site-packages/great_expectations_provider/operators/great_expectations.py", line 30, in <module>
    from great_expectations.checkpoint.types.checkpoint_result import CheckpointResult
ModuleNotFoundError: No module named 'great_expectations.checkpoint.types'
[2025-02-07T00:35:33.896+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/gx.py
[2025-02-07T00:35:33.917+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/gx.py took 2.066 seconds
[2025-02-07T00:36:04.058+0000] {processor.py:157} INFO - Started process (PID=4657) to work on /opt/airflow/dags/gx.py
[2025-02-07T00:36:04.059+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/gx.py for tasks to queue
[2025-02-07T00:36:04.061+0000] {logging_mixin.py:151} INFO - [2025-02-07T00:36:04.061+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/gx.py
[2025-02-07T00:36:05.686+0000] {logging_mixin.py:151} INFO - [2025-02-07T00:36:05.685+0000] {warnings.py:109} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:103: UserWarning: You have an incompatible version of 'pyarrow' installed (11.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
  warn_incompatible_dep(
[2025-02-07T00:36:06.039+0000] {logging_mixin.py:151} INFO - [2025-02-07T00:36:06.038+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/gx.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gx.py", line 3, in <module>
    from great_expectations_provider.operators.great_expectations import (
  File "/home/airflow/.local/lib/python3.8/site-packages/great_expectations_provider/operators/great_expectations.py", line 30, in <module>
    from great_expectations.checkpoint.types.checkpoint_result import CheckpointResult
ModuleNotFoundError: No module named 'great_expectations.checkpoint.types'
[2025-02-07T00:36:06.040+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/gx.py
[2025-02-07T00:36:06.060+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/gx.py took 2.005 seconds
[2025-02-07T00:36:36.270+0000] {processor.py:157} INFO - Started process (PID=4678) to work on /opt/airflow/dags/gx.py
[2025-02-07T00:36:36.271+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/gx.py for tasks to queue
[2025-02-07T00:36:36.273+0000] {logging_mixin.py:151} INFO - [2025-02-07T00:36:36.273+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/gx.py
[2025-02-07T00:36:37.873+0000] {logging_mixin.py:151} INFO - [2025-02-07T00:36:37.872+0000] {warnings.py:109} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:103: UserWarning: You have an incompatible version of 'pyarrow' installed (11.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
  warn_incompatible_dep(
[2025-02-07T00:36:38.269+0000] {logging_mixin.py:151} INFO - [2025-02-07T00:36:38.268+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/gx.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gx.py", line 3, in <module>
    from great_expectations_provider.operators.great_expectations import (
  File "/home/airflow/.local/lib/python3.8/site-packages/great_expectations_provider/operators/great_expectations.py", line 30, in <module>
    from great_expectations.checkpoint.types.checkpoint_result import CheckpointResult
ModuleNotFoundError: No module named 'great_expectations.checkpoint.types'
[2025-02-07T00:36:38.269+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/gx.py
[2025-02-07T00:36:38.290+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/gx.py took 2.024 seconds
[2025-02-07T00:37:08.490+0000] {processor.py:157} INFO - Started process (PID=4699) to work on /opt/airflow/dags/gx.py
[2025-02-07T00:37:08.491+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/gx.py for tasks to queue
[2025-02-07T00:37:08.494+0000] {logging_mixin.py:151} INFO - [2025-02-07T00:37:08.493+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/gx.py
[2025-02-07T00:37:10.179+0000] {logging_mixin.py:151} INFO - [2025-02-07T00:37:10.178+0000] {warnings.py:109} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:103: UserWarning: You have an incompatible version of 'pyarrow' installed (11.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
  warn_incompatible_dep(
[2025-02-07T00:37:10.527+0000] {logging_mixin.py:151} INFO - [2025-02-07T00:37:10.526+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/gx.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gx.py", line 3, in <module>
    from great_expectations_provider.operators.great_expectations import (
  File "/home/airflow/.local/lib/python3.8/site-packages/great_expectations_provider/operators/great_expectations.py", line 30, in <module>
    from great_expectations.checkpoint.types.checkpoint_result import CheckpointResult
ModuleNotFoundError: No module named 'great_expectations.checkpoint.types'
[2025-02-07T00:37:10.528+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/gx.py
[2025-02-07T00:37:10.549+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/gx.py took 2.062 seconds
[2025-02-07T00:37:40.729+0000] {processor.py:157} INFO - Started process (PID=4720) to work on /opt/airflow/dags/gx.py
[2025-02-07T00:37:40.731+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/gx.py for tasks to queue
[2025-02-07T00:37:40.736+0000] {logging_mixin.py:151} INFO - [2025-02-07T00:37:40.735+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/gx.py
[2025-02-07T00:37:42.309+0000] {logging_mixin.py:151} INFO - [2025-02-07T00:37:42.309+0000] {warnings.py:109} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:103: UserWarning: You have an incompatible version of 'pyarrow' installed (11.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
  warn_incompatible_dep(
[2025-02-07T00:37:42.650+0000] {logging_mixin.py:151} INFO - [2025-02-07T00:37:42.649+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/gx.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gx.py", line 3, in <module>
    from great_expectations_provider.operators.great_expectations import (
  File "/home/airflow/.local/lib/python3.8/site-packages/great_expectations_provider/operators/great_expectations.py", line 30, in <module>
    from great_expectations.checkpoint.types.checkpoint_result import CheckpointResult
ModuleNotFoundError: No module named 'great_expectations.checkpoint.types'
[2025-02-07T00:37:42.651+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/gx.py
[2025-02-07T00:37:42.671+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/gx.py took 1.950 seconds
[2025-02-07T00:38:12.917+0000] {processor.py:157} INFO - Started process (PID=4741) to work on /opt/airflow/dags/gx.py
[2025-02-07T00:38:12.918+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/gx.py for tasks to queue
[2025-02-07T00:38:12.922+0000] {logging_mixin.py:151} INFO - [2025-02-07T00:38:12.921+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/gx.py
[2025-02-07T00:38:14.557+0000] {logging_mixin.py:151} INFO - [2025-02-07T00:38:14.556+0000] {warnings.py:109} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:103: UserWarning: You have an incompatible version of 'pyarrow' installed (11.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
  warn_incompatible_dep(
[2025-02-07T00:38:14.905+0000] {logging_mixin.py:151} INFO - [2025-02-07T00:38:14.903+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/gx.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gx.py", line 3, in <module>
    from great_expectations_provider.operators.great_expectations import (
  File "/home/airflow/.local/lib/python3.8/site-packages/great_expectations_provider/operators/great_expectations.py", line 30, in <module>
    from great_expectations.checkpoint.types.checkpoint_result import CheckpointResult
ModuleNotFoundError: No module named 'great_expectations.checkpoint.types'
[2025-02-07T00:38:14.905+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/gx.py
[2025-02-07T00:38:14.917+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/gx.py took 2.002 seconds
[2025-02-07T00:38:45.119+0000] {processor.py:157} INFO - Started process (PID=4762) to work on /opt/airflow/dags/gx.py
[2025-02-07T00:38:45.120+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/gx.py for tasks to queue
[2025-02-07T00:38:45.122+0000] {logging_mixin.py:151} INFO - [2025-02-07T00:38:45.122+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/gx.py
[2025-02-07T00:38:46.734+0000] {logging_mixin.py:151} INFO - [2025-02-07T00:38:46.734+0000] {warnings.py:109} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:103: UserWarning: You have an incompatible version of 'pyarrow' installed (11.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
  warn_incompatible_dep(
[2025-02-07T00:38:47.084+0000] {logging_mixin.py:151} INFO - [2025-02-07T00:38:47.083+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/gx.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gx.py", line 3, in <module>
    from great_expectations_provider.operators.great_expectations import (
  File "/home/airflow/.local/lib/python3.8/site-packages/great_expectations_provider/operators/great_expectations.py", line 30, in <module>
    from great_expectations.checkpoint.types.checkpoint_result import CheckpointResult
ModuleNotFoundError: No module named 'great_expectations.checkpoint.types'
[2025-02-07T00:38:47.084+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/gx.py
[2025-02-07T00:38:47.105+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/gx.py took 1.989 seconds
[2025-02-07T00:39:17.262+0000] {processor.py:157} INFO - Started process (PID=4783) to work on /opt/airflow/dags/gx.py
[2025-02-07T00:39:17.263+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/gx.py for tasks to queue
[2025-02-07T00:39:17.265+0000] {logging_mixin.py:151} INFO - [2025-02-07T00:39:17.265+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/gx.py
[2025-02-07T00:39:19.131+0000] {logging_mixin.py:151} INFO - [2025-02-07T00:39:19.130+0000] {warnings.py:109} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:103: UserWarning: You have an incompatible version of 'pyarrow' installed (11.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
  warn_incompatible_dep(
[2025-02-07T00:39:19.555+0000] {logging_mixin.py:151} INFO - [2025-02-07T00:39:19.554+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/gx.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gx.py", line 3, in <module>
    from great_expectations_provider.operators.great_expectations import (
  File "/home/airflow/.local/lib/python3.8/site-packages/great_expectations_provider/operators/great_expectations.py", line 30, in <module>
    from great_expectations.checkpoint.types.checkpoint_result import CheckpointResult
ModuleNotFoundError: No module named 'great_expectations.checkpoint.types'
[2025-02-07T00:39:19.556+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/gx.py
[2025-02-07T00:39:19.582+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/gx.py took 2.323 seconds
[2025-02-07T00:39:49.727+0000] {processor.py:157} INFO - Started process (PID=4804) to work on /opt/airflow/dags/gx.py
[2025-02-07T00:39:49.728+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/gx.py for tasks to queue
[2025-02-07T00:39:49.730+0000] {logging_mixin.py:151} INFO - [2025-02-07T00:39:49.730+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/gx.py
[2025-02-07T00:39:51.923+0000] {logging_mixin.py:151} INFO - [2025-02-07T00:39:51.922+0000] {warnings.py:109} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:103: UserWarning: You have an incompatible version of 'pyarrow' installed (11.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
  warn_incompatible_dep(
[2025-02-07T00:39:52.326+0000] {logging_mixin.py:151} INFO - [2025-02-07T00:39:52.325+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/gx.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gx.py", line 3, in <module>
    from great_expectations_provider.operators.great_expectations import (
  File "/home/airflow/.local/lib/python3.8/site-packages/great_expectations_provider/operators/great_expectations.py", line 30, in <module>
    from great_expectations.checkpoint.types.checkpoint_result import CheckpointResult
ModuleNotFoundError: No module named 'great_expectations.checkpoint.types'
[2025-02-07T00:39:52.326+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/gx.py
[2025-02-07T00:39:52.349+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/gx.py took 2.625 seconds
[2025-02-07T00:40:22.508+0000] {processor.py:157} INFO - Started process (PID=4825) to work on /opt/airflow/dags/gx.py
[2025-02-07T00:40:22.509+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/gx.py for tasks to queue
[2025-02-07T00:40:22.511+0000] {logging_mixin.py:151} INFO - [2025-02-07T00:40:22.511+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/gx.py
[2025-02-07T00:40:23.590+0000] {logging_mixin.py:151} INFO - [2025-02-07T00:40:23.589+0000] {warnings.py:109} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:103: UserWarning: You have an incompatible version of 'pyarrow' installed (11.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
  warn_incompatible_dep(
[2025-02-07T00:40:24.002+0000] {logging_mixin.py:151} INFO - [2025-02-07T00:40:24.001+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/gx.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gx.py", line 3, in <module>
    from great_expectations_provider.operators.great_expectations import (
  File "/home/airflow/.local/lib/python3.8/site-packages/great_expectations_provider/operators/great_expectations.py", line 30, in <module>
    from great_expectations.checkpoint.types.checkpoint_result import CheckpointResult
ModuleNotFoundError: No module named 'great_expectations.checkpoint.types'
[2025-02-07T00:40:24.002+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/gx.py
[2025-02-07T00:40:24.018+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/gx.py took 2.324 seconds
[2025-02-07T00:40:54.181+0000] {processor.py:157} INFO - Started process (PID=4846) to work on /opt/airflow/dags/gx.py
[2025-02-07T00:40:54.182+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/gx.py for tasks to queue
[2025-02-07T00:40:54.185+0000] {logging_mixin.py:151} INFO - [2025-02-07T00:40:54.184+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/gx.py
[2025-02-07T00:40:56.018+0000] {logging_mixin.py:151} INFO - [2025-02-07T00:40:56.017+0000] {warnings.py:109} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:103: UserWarning: You have an incompatible version of 'pyarrow' installed (11.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
  warn_incompatible_dep(
[2025-02-07T00:40:56.418+0000] {logging_mixin.py:151} INFO - [2025-02-07T00:40:56.417+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/gx.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gx.py", line 3, in <module>
    from great_expectations_provider.operators.great_expectations import (
  File "/home/airflow/.local/lib/python3.8/site-packages/great_expectations_provider/operators/great_expectations.py", line 30, in <module>
    from great_expectations.checkpoint.types.checkpoint_result import CheckpointResult
ModuleNotFoundError: No module named 'great_expectations.checkpoint.types'
[2025-02-07T00:40:56.419+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/gx.py
[2025-02-07T00:40:56.434+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/gx.py took 2.257 seconds
[2025-02-07T00:41:26.582+0000] {processor.py:157} INFO - Started process (PID=4867) to work on /opt/airflow/dags/gx.py
[2025-02-07T00:41:26.583+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/gx.py for tasks to queue
[2025-02-07T00:41:26.586+0000] {logging_mixin.py:151} INFO - [2025-02-07T00:41:26.585+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/gx.py
[2025-02-07T00:41:28.418+0000] {logging_mixin.py:151} INFO - [2025-02-07T00:41:28.417+0000] {warnings.py:109} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:103: UserWarning: You have an incompatible version of 'pyarrow' installed (11.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
  warn_incompatible_dep(
[2025-02-07T00:41:28.827+0000] {logging_mixin.py:151} INFO - [2025-02-07T00:41:28.826+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/gx.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gx.py", line 3, in <module>
    from great_expectations_provider.operators.great_expectations import (
  File "/home/airflow/.local/lib/python3.8/site-packages/great_expectations_provider/operators/great_expectations.py", line 30, in <module>
    from great_expectations.checkpoint.types.checkpoint_result import CheckpointResult
ModuleNotFoundError: No module named 'great_expectations.checkpoint.types'
[2025-02-07T00:41:28.827+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/gx.py
[2025-02-07T00:41:28.857+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/gx.py took 2.278 seconds
[2025-02-07T00:41:58.994+0000] {processor.py:157} INFO - Started process (PID=4895) to work on /opt/airflow/dags/gx.py
[2025-02-07T00:41:58.995+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/gx.py for tasks to queue
[2025-02-07T00:41:58.998+0000] {logging_mixin.py:151} INFO - [2025-02-07T00:41:58.997+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/gx.py
[2025-02-07T00:42:00.891+0000] {logging_mixin.py:151} INFO - [2025-02-07T00:42:00.890+0000] {warnings.py:109} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:103: UserWarning: You have an incompatible version of 'pyarrow' installed (11.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
  warn_incompatible_dep(
[2025-02-07T00:42:01.335+0000] {logging_mixin.py:151} INFO - [2025-02-07T00:42:01.334+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/gx.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gx.py", line 3, in <module>
    from great_expectations_provider.operators.great_expectations import (
  File "/home/airflow/.local/lib/python3.8/site-packages/great_expectations_provider/operators/great_expectations.py", line 30, in <module>
    from great_expectations.checkpoint.types.checkpoint_result import CheckpointResult
ModuleNotFoundError: No module named 'great_expectations.checkpoint.types'
[2025-02-07T00:42:01.336+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/gx.py
[2025-02-07T00:42:01.360+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/gx.py took 2.369 seconds
[2025-02-07T00:42:31.516+0000] {processor.py:157} INFO - Started process (PID=4916) to work on /opt/airflow/dags/gx.py
[2025-02-07T00:42:31.517+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/gx.py for tasks to queue
[2025-02-07T00:42:31.520+0000] {logging_mixin.py:151} INFO - [2025-02-07T00:42:31.519+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/gx.py
[2025-02-07T00:42:33.268+0000] {logging_mixin.py:151} INFO - [2025-02-07T00:42:33.267+0000] {warnings.py:109} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:103: UserWarning: You have an incompatible version of 'pyarrow' installed (11.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
  warn_incompatible_dep(
[2025-02-07T00:42:33.615+0000] {logging_mixin.py:151} INFO - [2025-02-07T00:42:33.613+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/gx.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gx.py", line 3, in <module>
    from great_expectations_provider.operators.great_expectations import (
  File "/home/airflow/.local/lib/python3.8/site-packages/great_expectations_provider/operators/great_expectations.py", line 30, in <module>
    from great_expectations.checkpoint.types.checkpoint_result import CheckpointResult
ModuleNotFoundError: No module named 'great_expectations.checkpoint.types'
[2025-02-07T00:42:33.615+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/gx.py
[2025-02-07T00:42:33.636+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/gx.py took 2.124 seconds
[2025-02-07T00:43:03.703+0000] {processor.py:157} INFO - Started process (PID=4937) to work on /opt/airflow/dags/gx.py
[2025-02-07T00:43:03.704+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/gx.py for tasks to queue
[2025-02-07T00:43:03.708+0000] {logging_mixin.py:151} INFO - [2025-02-07T00:43:03.708+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/gx.py
[2025-02-07T00:43:06.150+0000] {logging_mixin.py:151} INFO - [2025-02-07T00:43:06.149+0000] {warnings.py:109} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:103: UserWarning: You have an incompatible version of 'pyarrow' installed (11.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
  warn_incompatible_dep(
[2025-02-07T00:43:06.605+0000] {logging_mixin.py:151} INFO - [2025-02-07T00:43:06.603+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/gx.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gx.py", line 3, in <module>
    from great_expectations_provider.operators.great_expectations import (
  File "/home/airflow/.local/lib/python3.8/site-packages/great_expectations_provider/operators/great_expectations.py", line 30, in <module>
    from great_expectations.checkpoint.types.checkpoint_result import CheckpointResult
ModuleNotFoundError: No module named 'great_expectations.checkpoint.types'
[2025-02-07T00:43:06.606+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/gx.py
[2025-02-07T00:43:06.626+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/gx.py took 2.927 seconds
[2025-02-07T00:43:36.848+0000] {processor.py:157} INFO - Started process (PID=4958) to work on /opt/airflow/dags/gx.py
[2025-02-07T00:43:36.850+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/gx.py for tasks to queue
[2025-02-07T00:43:36.854+0000] {logging_mixin.py:151} INFO - [2025-02-07T00:43:36.854+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/gx.py
