[2025-02-22T08:37:42.814+0000] {processor.py:157} INFO - Started process (PID=53) to work on /opt/airflow/dags/gx.py
[2025-02-22T08:37:42.815+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/gx.py for tasks to queue
[2025-02-22T08:37:42.819+0000] {logging_mixin.py:151} INFO - [2025-02-22T08:37:42.818+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/gx.py
[2025-02-22T08:37:48.889+0000] {logging_mixin.py:151} INFO - [2025-02-22T08:37:48.888+0000] {warnings.py:109} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:103: UserWarning: You have an incompatible version of 'pyarrow' installed (11.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
  warn_incompatible_dep(
[2025-02-22T08:37:49.872+0000] {logging_mixin.py:151} INFO - [2025-02-22T08:37:49.870+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/gx.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gx.py", line 3, in <module>
    from great_expectations_provider.operators.great_expectations import (
  File "/home/airflow/.local/lib/python3.8/site-packages/great_expectations_provider/operators/great_expectations.py", line 30, in <module>
    from great_expectations.checkpoint.types.checkpoint_result import CheckpointResult
ModuleNotFoundError: No module named 'great_expectations.checkpoint.types'
[2025-02-22T08:37:49.873+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/gx.py
[2025-02-22T08:37:49.893+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/gx.py took 7.083 seconds
[2025-02-22T08:38:20.061+0000] {processor.py:157} INFO - Started process (PID=81) to work on /opt/airflow/dags/gx.py
[2025-02-22T08:38:20.062+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/gx.py for tasks to queue
[2025-02-22T08:38:20.064+0000] {logging_mixin.py:151} INFO - [2025-02-22T08:38:20.064+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/gx.py
[2025-02-22T08:38:30.295+0000] {logging_mixin.py:151} INFO - [2025-02-22T08:38:30.294+0000] {warnings.py:109} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:103: UserWarning: You have an incompatible version of 'pyarrow' installed (11.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
  warn_incompatible_dep(
[2025-02-22T08:38:31.073+0000] {logging_mixin.py:151} INFO - [2025-02-22T08:38:31.072+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/gx.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gx.py", line 3, in <module>
    from great_expectations_provider.operators.great_expectations import (
  File "/home/airflow/.local/lib/python3.8/site-packages/great_expectations_provider/operators/great_expectations.py", line 30, in <module>
    from great_expectations.checkpoint.types.checkpoint_result import CheckpointResult
ModuleNotFoundError: No module named 'great_expectations.checkpoint.types'
[2025-02-22T08:38:31.074+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/gx.py
[2025-02-22T08:38:31.119+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/gx.py took 11.062 seconds
[2025-02-22T08:39:01.266+0000] {processor.py:157} INFO - Started process (PID=102) to work on /opt/airflow/dags/gx.py
[2025-02-22T08:39:01.267+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/gx.py for tasks to queue
[2025-02-22T08:39:01.269+0000] {logging_mixin.py:151} INFO - [2025-02-22T08:39:01.269+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/gx.py
[2025-02-22T08:39:03.136+0000] {logging_mixin.py:151} INFO - [2025-02-22T08:39:03.136+0000] {warnings.py:109} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:103: UserWarning: You have an incompatible version of 'pyarrow' installed (11.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
  warn_incompatible_dep(
[2025-02-22T08:39:03.730+0000] {logging_mixin.py:151} INFO - [2025-02-22T08:39:03.729+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/gx.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gx.py", line 3, in <module>
    from great_expectations_provider.operators.great_expectations import (
  File "/home/airflow/.local/lib/python3.8/site-packages/great_expectations_provider/operators/great_expectations.py", line 30, in <module>
    from great_expectations.checkpoint.types.checkpoint_result import CheckpointResult
ModuleNotFoundError: No module named 'great_expectations.checkpoint.types'
[2025-02-22T08:39:03.730+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/gx.py
[2025-02-22T08:39:03.747+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/gx.py took 2.484 seconds
[2025-02-22T08:39:33.918+0000] {processor.py:157} INFO - Started process (PID=123) to work on /opt/airflow/dags/gx.py
[2025-02-22T08:39:33.918+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/gx.py for tasks to queue
[2025-02-22T08:39:33.921+0000] {logging_mixin.py:151} INFO - [2025-02-22T08:39:33.920+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/gx.py
[2025-02-22T08:39:35.833+0000] {logging_mixin.py:151} INFO - [2025-02-22T08:39:35.832+0000] {warnings.py:109} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:103: UserWarning: You have an incompatible version of 'pyarrow' installed (11.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
  warn_incompatible_dep(
[2025-02-22T08:39:36.383+0000] {logging_mixin.py:151} INFO - [2025-02-22T08:39:36.382+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/gx.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gx.py", line 3, in <module>
    from great_expectations_provider.operators.great_expectations import (
  File "/home/airflow/.local/lib/python3.8/site-packages/great_expectations_provider/operators/great_expectations.py", line 30, in <module>
    from great_expectations.checkpoint.types.checkpoint_result import CheckpointResult
ModuleNotFoundError: No module named 'great_expectations.checkpoint.types'
[2025-02-22T08:39:36.384+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/gx.py
[2025-02-22T08:39:36.397+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/gx.py took 2.482 seconds
[2025-02-22T08:40:06.549+0000] {processor.py:157} INFO - Started process (PID=144) to work on /opt/airflow/dags/gx.py
[2025-02-22T08:40:06.551+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/gx.py for tasks to queue
[2025-02-22T08:40:06.553+0000] {logging_mixin.py:151} INFO - [2025-02-22T08:40:06.553+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/gx.py
[2025-02-22T08:40:08.527+0000] {logging_mixin.py:151} INFO - [2025-02-22T08:40:08.526+0000] {warnings.py:109} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:103: UserWarning: You have an incompatible version of 'pyarrow' installed (11.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
  warn_incompatible_dep(
[2025-02-22T08:40:09.114+0000] {logging_mixin.py:151} INFO - [2025-02-22T08:40:09.113+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/gx.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gx.py", line 3, in <module>
    from great_expectations_provider.operators.great_expectations import (
  File "/home/airflow/.local/lib/python3.8/site-packages/great_expectations_provider/operators/great_expectations.py", line 30, in <module>
    from great_expectations.checkpoint.types.checkpoint_result import CheckpointResult
ModuleNotFoundError: No module named 'great_expectations.checkpoint.types'
[2025-02-22T08:40:09.115+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/gx.py
[2025-02-22T08:40:09.129+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/gx.py took 2.583 seconds
[2025-02-22T08:40:39.208+0000] {processor.py:157} INFO - Started process (PID=165) to work on /opt/airflow/dags/gx.py
[2025-02-22T08:40:39.209+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/gx.py for tasks to queue
[2025-02-22T08:40:39.212+0000] {logging_mixin.py:151} INFO - [2025-02-22T08:40:39.212+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/gx.py
[2025-02-22T08:40:41.078+0000] {logging_mixin.py:151} INFO - [2025-02-22T08:40:41.077+0000] {warnings.py:109} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:103: UserWarning: You have an incompatible version of 'pyarrow' installed (11.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
  warn_incompatible_dep(
[2025-02-22T08:40:41.677+0000] {logging_mixin.py:151} INFO - [2025-02-22T08:40:41.676+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/gx.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gx.py", line 3, in <module>
    from great_expectations_provider.operators.great_expectations import (
  File "/home/airflow/.local/lib/python3.8/site-packages/great_expectations_provider/operators/great_expectations.py", line 30, in <module>
    from great_expectations.checkpoint.types.checkpoint_result import CheckpointResult
ModuleNotFoundError: No module named 'great_expectations.checkpoint.types'
[2025-02-22T08:40:41.678+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/gx.py
[2025-02-22T08:40:41.699+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/gx.py took 2.494 seconds
[2025-02-22T08:41:11.850+0000] {processor.py:157} INFO - Started process (PID=185) to work on /opt/airflow/dags/gx.py
[2025-02-22T08:41:11.851+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/gx.py for tasks to queue
[2025-02-22T08:41:11.855+0000] {logging_mixin.py:151} INFO - [2025-02-22T08:41:11.855+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/gx.py
[2025-02-22T08:41:13.763+0000] {logging_mixin.py:151} INFO - [2025-02-22T08:41:13.762+0000] {warnings.py:109} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:103: UserWarning: You have an incompatible version of 'pyarrow' installed (11.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
  warn_incompatible_dep(
[2025-02-22T08:41:14.370+0000] {logging_mixin.py:151} INFO - [2025-02-22T08:41:14.368+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/gx.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gx.py", line 3, in <module>
    from great_expectations_provider.operators.great_expectations import (
  File "/home/airflow/.local/lib/python3.8/site-packages/great_expectations_provider/operators/great_expectations.py", line 30, in <module>
    from great_expectations.checkpoint.types.checkpoint_result import CheckpointResult
ModuleNotFoundError: No module named 'great_expectations.checkpoint.types'
[2025-02-22T08:41:14.370+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/gx.py
[2025-02-22T08:41:14.390+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/gx.py took 2.544 seconds
[2025-02-22T08:41:44.573+0000] {processor.py:157} INFO - Started process (PID=206) to work on /opt/airflow/dags/gx.py
[2025-02-22T08:41:44.574+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/gx.py for tasks to queue
[2025-02-22T08:41:44.576+0000] {logging_mixin.py:151} INFO - [2025-02-22T08:41:44.576+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/gx.py
[2025-02-22T08:41:46.499+0000] {logging_mixin.py:151} INFO - [2025-02-22T08:41:46.499+0000] {warnings.py:109} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:103: UserWarning: You have an incompatible version of 'pyarrow' installed (11.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
  warn_incompatible_dep(
[2025-02-22T08:41:47.076+0000] {logging_mixin.py:151} INFO - [2025-02-22T08:41:47.075+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/gx.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gx.py", line 3, in <module>
    from great_expectations_provider.operators.great_expectations import (
  File "/home/airflow/.local/lib/python3.8/site-packages/great_expectations_provider/operators/great_expectations.py", line 30, in <module>
    from great_expectations.checkpoint.types.checkpoint_result import CheckpointResult
ModuleNotFoundError: No module named 'great_expectations.checkpoint.types'
[2025-02-22T08:41:47.077+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/gx.py
[2025-02-22T08:41:47.089+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/gx.py took 2.519 seconds
[2025-02-22T08:42:17.171+0000] {processor.py:157} INFO - Started process (PID=234) to work on /opt/airflow/dags/gx.py
[2025-02-22T08:42:17.172+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/gx.py for tasks to queue
[2025-02-22T08:42:17.176+0000] {logging_mixin.py:151} INFO - [2025-02-22T08:42:17.175+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/gx.py
[2025-02-22T08:42:19.414+0000] {logging_mixin.py:151} INFO - [2025-02-22T08:42:19.413+0000] {warnings.py:109} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:103: UserWarning: You have an incompatible version of 'pyarrow' installed (11.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
  warn_incompatible_dep(
[2025-02-22T08:42:19.981+0000] {logging_mixin.py:151} INFO - [2025-02-22T08:42:19.979+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/gx.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gx.py", line 3, in <module>
    from great_expectations_provider.operators.great_expectations import (
  File "/home/airflow/.local/lib/python3.8/site-packages/great_expectations_provider/operators/great_expectations.py", line 30, in <module>
    from great_expectations.checkpoint.types.checkpoint_result import CheckpointResult
ModuleNotFoundError: No module named 'great_expectations.checkpoint.types'
[2025-02-22T08:42:19.981+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/gx.py
[2025-02-22T08:42:19.995+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/gx.py took 2.833 seconds
[2025-02-22T08:42:50.209+0000] {processor.py:157} INFO - Started process (PID=255) to work on /opt/airflow/dags/gx.py
[2025-02-22T08:42:50.211+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/gx.py for tasks to queue
[2025-02-22T08:42:50.214+0000] {logging_mixin.py:151} INFO - [2025-02-22T08:42:50.214+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/gx.py
[2025-02-22T08:42:51.986+0000] {logging_mixin.py:151} INFO - [2025-02-22T08:42:51.985+0000] {warnings.py:109} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:103: UserWarning: You have an incompatible version of 'pyarrow' installed (11.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
  warn_incompatible_dep(
[2025-02-22T08:42:52.503+0000] {logging_mixin.py:151} INFO - [2025-02-22T08:42:52.502+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/gx.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gx.py", line 3, in <module>
    from great_expectations_provider.operators.great_expectations import (
  File "/home/airflow/.local/lib/python3.8/site-packages/great_expectations_provider/operators/great_expectations.py", line 30, in <module>
    from great_expectations.checkpoint.types.checkpoint_result import CheckpointResult
ModuleNotFoundError: No module named 'great_expectations.checkpoint.types'
[2025-02-22T08:42:52.504+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/gx.py
[2025-02-22T08:42:52.531+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/gx.py took 2.327 seconds
[2025-02-22T08:43:22.580+0000] {processor.py:157} INFO - Started process (PID=276) to work on /opt/airflow/dags/gx.py
[2025-02-22T08:43:22.580+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/gx.py for tasks to queue
[2025-02-22T08:43:22.583+0000] {logging_mixin.py:151} INFO - [2025-02-22T08:43:22.583+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/gx.py
[2025-02-22T08:43:24.233+0000] {logging_mixin.py:151} INFO - [2025-02-22T08:43:24.232+0000] {warnings.py:109} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:103: UserWarning: You have an incompatible version of 'pyarrow' installed (11.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
  warn_incompatible_dep(
[2025-02-22T08:43:24.751+0000] {logging_mixin.py:151} INFO - [2025-02-22T08:43:24.750+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/gx.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gx.py", line 3, in <module>
    from great_expectations_provider.operators.great_expectations import (
  File "/home/airflow/.local/lib/python3.8/site-packages/great_expectations_provider/operators/great_expectations.py", line 30, in <module>
    from great_expectations.checkpoint.types.checkpoint_result import CheckpointResult
ModuleNotFoundError: No module named 'great_expectations.checkpoint.types'
[2025-02-22T08:43:24.752+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/gx.py
[2025-02-22T08:43:24.773+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/gx.py took 2.196 seconds
[2025-02-22T08:43:54.894+0000] {processor.py:157} INFO - Started process (PID=297) to work on /opt/airflow/dags/gx.py
[2025-02-22T08:43:54.895+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/gx.py for tasks to queue
[2025-02-22T08:43:54.898+0000] {logging_mixin.py:151} INFO - [2025-02-22T08:43:54.897+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/gx.py
[2025-02-22T08:43:56.511+0000] {logging_mixin.py:151} INFO - [2025-02-22T08:43:56.510+0000] {warnings.py:109} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:103: UserWarning: You have an incompatible version of 'pyarrow' installed (11.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
  warn_incompatible_dep(
[2025-02-22T08:43:57.072+0000] {logging_mixin.py:151} INFO - [2025-02-22T08:43:57.070+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/gx.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gx.py", line 3, in <module>
    from great_expectations_provider.operators.great_expectations import (
  File "/home/airflow/.local/lib/python3.8/site-packages/great_expectations_provider/operators/great_expectations.py", line 30, in <module>
    from great_expectations.checkpoint.types.checkpoint_result import CheckpointResult
ModuleNotFoundError: No module named 'great_expectations.checkpoint.types'
[2025-02-22T08:43:57.072+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/gx.py
[2025-02-22T08:43:57.091+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/gx.py took 2.200 seconds
[2025-02-22T08:44:27.260+0000] {processor.py:157} INFO - Started process (PID=318) to work on /opt/airflow/dags/gx.py
[2025-02-22T08:44:27.262+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/gx.py for tasks to queue
[2025-02-22T08:44:27.264+0000] {logging_mixin.py:151} INFO - [2025-02-22T08:44:27.264+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/gx.py
[2025-02-22T08:44:28.959+0000] {logging_mixin.py:151} INFO - [2025-02-22T08:44:28.958+0000] {warnings.py:109} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:103: UserWarning: You have an incompatible version of 'pyarrow' installed (11.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
  warn_incompatible_dep(
[2025-02-22T08:44:29.527+0000] {logging_mixin.py:151} INFO - [2025-02-22T08:44:29.526+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/gx.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gx.py", line 3, in <module>
    from great_expectations_provider.operators.great_expectations import (
  File "/home/airflow/.local/lib/python3.8/site-packages/great_expectations_provider/operators/great_expectations.py", line 30, in <module>
    from great_expectations.checkpoint.types.checkpoint_result import CheckpointResult
ModuleNotFoundError: No module named 'great_expectations.checkpoint.types'
[2025-02-22T08:44:29.527+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/gx.py
[2025-02-22T08:44:29.540+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/gx.py took 2.288 seconds
[2025-02-22T08:44:59.681+0000] {processor.py:157} INFO - Started process (PID=339) to work on /opt/airflow/dags/gx.py
[2025-02-22T08:44:59.682+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/gx.py for tasks to queue
[2025-02-22T08:44:59.684+0000] {logging_mixin.py:151} INFO - [2025-02-22T08:44:59.684+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/gx.py
[2025-02-22T08:45:01.373+0000] {logging_mixin.py:151} INFO - [2025-02-22T08:45:01.372+0000] {warnings.py:109} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:103: UserWarning: You have an incompatible version of 'pyarrow' installed (11.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
  warn_incompatible_dep(
[2025-02-22T08:45:01.964+0000] {logging_mixin.py:151} INFO - [2025-02-22T08:45:01.963+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/gx.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gx.py", line 3, in <module>
    from great_expectations_provider.operators.great_expectations import (
  File "/home/airflow/.local/lib/python3.8/site-packages/great_expectations_provider/operators/great_expectations.py", line 30, in <module>
    from great_expectations.checkpoint.types.checkpoint_result import CheckpointResult
ModuleNotFoundError: No module named 'great_expectations.checkpoint.types'
[2025-02-22T08:45:01.964+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/gx.py
[2025-02-22T08:45:01.985+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/gx.py took 2.307 seconds
[2025-02-22T08:45:32.146+0000] {processor.py:157} INFO - Started process (PID=360) to work on /opt/airflow/dags/gx.py
[2025-02-22T08:45:32.148+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/gx.py for tasks to queue
[2025-02-22T08:45:32.150+0000] {logging_mixin.py:151} INFO - [2025-02-22T08:45:32.150+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/gx.py
[2025-02-22T08:45:33.798+0000] {logging_mixin.py:151} INFO - [2025-02-22T08:45:33.798+0000] {warnings.py:109} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:103: UserWarning: You have an incompatible version of 'pyarrow' installed (11.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
  warn_incompatible_dep(
[2025-02-22T08:45:34.352+0000] {logging_mixin.py:151} INFO - [2025-02-22T08:45:34.351+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/gx.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gx.py", line 3, in <module>
    from great_expectations_provider.operators.great_expectations import (
  File "/home/airflow/.local/lib/python3.8/site-packages/great_expectations_provider/operators/great_expectations.py", line 30, in <module>
    from great_expectations.checkpoint.types.checkpoint_result import CheckpointResult
ModuleNotFoundError: No module named 'great_expectations.checkpoint.types'
[2025-02-22T08:45:34.353+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/gx.py
[2025-02-22T08:45:34.375+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/gx.py took 2.231 seconds
[2025-02-22T08:46:04.562+0000] {processor.py:157} INFO - Started process (PID=381) to work on /opt/airflow/dags/gx.py
[2025-02-22T08:46:04.562+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/gx.py for tasks to queue
[2025-02-22T08:46:04.566+0000] {logging_mixin.py:151} INFO - [2025-02-22T08:46:04.566+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/gx.py
[2025-02-22T08:46:06.272+0000] {logging_mixin.py:151} INFO - [2025-02-22T08:46:06.272+0000] {warnings.py:109} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:103: UserWarning: You have an incompatible version of 'pyarrow' installed (11.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
  warn_incompatible_dep(
[2025-02-22T08:46:06.831+0000] {logging_mixin.py:151} INFO - [2025-02-22T08:46:06.830+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/gx.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gx.py", line 3, in <module>
    from great_expectations_provider.operators.great_expectations import (
  File "/home/airflow/.local/lib/python3.8/site-packages/great_expectations_provider/operators/great_expectations.py", line 30, in <module>
    from great_expectations.checkpoint.types.checkpoint_result import CheckpointResult
ModuleNotFoundError: No module named 'great_expectations.checkpoint.types'
[2025-02-22T08:46:06.831+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/gx.py
[2025-02-22T08:46:06.843+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/gx.py took 2.285 seconds
[2025-02-22T08:46:37.017+0000] {processor.py:157} INFO - Started process (PID=402) to work on /opt/airflow/dags/gx.py
[2025-02-22T08:46:37.019+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/gx.py for tasks to queue
[2025-02-22T08:46:37.023+0000] {logging_mixin.py:151} INFO - [2025-02-22T08:46:37.022+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/gx.py
[2025-02-22T08:46:38.770+0000] {logging_mixin.py:151} INFO - [2025-02-22T08:46:38.770+0000] {warnings.py:109} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:103: UserWarning: You have an incompatible version of 'pyarrow' installed (11.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
  warn_incompatible_dep(
[2025-02-22T08:46:39.316+0000] {logging_mixin.py:151} INFO - [2025-02-22T08:46:39.315+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/gx.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gx.py", line 3, in <module>
    from great_expectations_provider.operators.great_expectations import (
  File "/home/airflow/.local/lib/python3.8/site-packages/great_expectations_provider/operators/great_expectations.py", line 30, in <module>
    from great_expectations.checkpoint.types.checkpoint_result import CheckpointResult
ModuleNotFoundError: No module named 'great_expectations.checkpoint.types'
[2025-02-22T08:46:39.317+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/gx.py
[2025-02-22T08:46:39.337+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/gx.py took 2.328 seconds
[2025-02-22T08:47:09.516+0000] {processor.py:157} INFO - Started process (PID=423) to work on /opt/airflow/dags/gx.py
[2025-02-22T08:47:09.518+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/gx.py for tasks to queue
[2025-02-22T08:47:09.520+0000] {logging_mixin.py:151} INFO - [2025-02-22T08:47:09.520+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/gx.py
[2025-02-22T08:47:11.170+0000] {logging_mixin.py:151} INFO - [2025-02-22T08:47:11.169+0000] {warnings.py:109} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:103: UserWarning: You have an incompatible version of 'pyarrow' installed (11.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
  warn_incompatible_dep(
[2025-02-22T08:47:11.705+0000] {logging_mixin.py:151} INFO - [2025-02-22T08:47:11.704+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/gx.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gx.py", line 3, in <module>
    from great_expectations_provider.operators.great_expectations import (
  File "/home/airflow/.local/lib/python3.8/site-packages/great_expectations_provider/operators/great_expectations.py", line 30, in <module>
    from great_expectations.checkpoint.types.checkpoint_result import CheckpointResult
ModuleNotFoundError: No module named 'great_expectations.checkpoint.types'
[2025-02-22T08:47:11.705+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/gx.py
[2025-02-22T08:47:11.726+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/gx.py took 2.217 seconds
[2025-02-22T08:47:41.920+0000] {processor.py:157} INFO - Started process (PID=444) to work on /opt/airflow/dags/gx.py
[2025-02-22T08:47:41.921+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/gx.py for tasks to queue
[2025-02-22T08:47:41.923+0000] {logging_mixin.py:151} INFO - [2025-02-22T08:47:41.922+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/gx.py
[2025-02-22T08:47:43.690+0000] {logging_mixin.py:151} INFO - [2025-02-22T08:47:43.689+0000] {warnings.py:109} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:103: UserWarning: You have an incompatible version of 'pyarrow' installed (11.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
  warn_incompatible_dep(
[2025-02-22T08:47:44.296+0000] {logging_mixin.py:151} INFO - [2025-02-22T08:47:44.294+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/gx.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gx.py", line 3, in <module>
    from great_expectations_provider.operators.great_expectations import (
  File "/home/airflow/.local/lib/python3.8/site-packages/great_expectations_provider/operators/great_expectations.py", line 30, in <module>
    from great_expectations.checkpoint.types.checkpoint_result import CheckpointResult
ModuleNotFoundError: No module named 'great_expectations.checkpoint.types'
[2025-02-22T08:47:44.296+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/gx.py
[2025-02-22T08:47:44.318+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/gx.py took 2.406 seconds
[2025-02-22T08:48:14.503+0000] {processor.py:157} INFO - Started process (PID=465) to work on /opt/airflow/dags/gx.py
[2025-02-22T08:48:14.504+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/gx.py for tasks to queue
[2025-02-22T08:48:14.507+0000] {logging_mixin.py:151} INFO - [2025-02-22T08:48:14.506+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/gx.py
[2025-02-22T08:48:16.442+0000] {logging_mixin.py:151} INFO - [2025-02-22T08:48:16.441+0000] {warnings.py:109} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:103: UserWarning: You have an incompatible version of 'pyarrow' installed (11.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
  warn_incompatible_dep(
[2025-02-22T08:48:17.000+0000] {logging_mixin.py:151} INFO - [2025-02-22T08:48:16.998+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/gx.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gx.py", line 3, in <module>
    from great_expectations_provider.operators.great_expectations import (
  File "/home/airflow/.local/lib/python3.8/site-packages/great_expectations_provider/operators/great_expectations.py", line 30, in <module>
    from great_expectations.checkpoint.types.checkpoint_result import CheckpointResult
ModuleNotFoundError: No module named 'great_expectations.checkpoint.types'
[2025-02-22T08:48:17.000+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/gx.py
[2025-02-22T08:48:17.020+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/gx.py took 2.519 seconds
[2025-02-22T08:48:47.210+0000] {processor.py:157} INFO - Started process (PID=493) to work on /opt/airflow/dags/gx.py
[2025-02-22T08:48:47.211+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/gx.py for tasks to queue
[2025-02-22T08:48:47.215+0000] {logging_mixin.py:151} INFO - [2025-02-22T08:48:47.214+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/gx.py
[2025-02-22T08:48:48.854+0000] {logging_mixin.py:151} INFO - [2025-02-22T08:48:48.853+0000] {warnings.py:109} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:103: UserWarning: You have an incompatible version of 'pyarrow' installed (11.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
  warn_incompatible_dep(
[2025-02-22T08:48:49.379+0000] {logging_mixin.py:151} INFO - [2025-02-22T08:48:49.378+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/gx.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gx.py", line 3, in <module>
    from great_expectations_provider.operators.great_expectations import (
  File "/home/airflow/.local/lib/python3.8/site-packages/great_expectations_provider/operators/great_expectations.py", line 30, in <module>
    from great_expectations.checkpoint.types.checkpoint_result import CheckpointResult
ModuleNotFoundError: No module named 'great_expectations.checkpoint.types'
[2025-02-22T08:48:49.379+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/gx.py
[2025-02-22T08:48:49.400+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/gx.py took 2.192 seconds
[2025-02-22T08:49:19.569+0000] {processor.py:157} INFO - Started process (PID=514) to work on /opt/airflow/dags/gx.py
[2025-02-22T08:49:19.570+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/gx.py for tasks to queue
[2025-02-22T08:49:19.572+0000] {logging_mixin.py:151} INFO - [2025-02-22T08:49:19.572+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/gx.py
[2025-02-22T08:49:21.269+0000] {logging_mixin.py:151} INFO - [2025-02-22T08:49:21.269+0000] {warnings.py:109} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:103: UserWarning: You have an incompatible version of 'pyarrow' installed (11.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
  warn_incompatible_dep(
[2025-02-22T08:49:21.810+0000] {logging_mixin.py:151} INFO - [2025-02-22T08:49:21.809+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/gx.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gx.py", line 3, in <module>
    from great_expectations_provider.operators.great_expectations import (
  File "/home/airflow/.local/lib/python3.8/site-packages/great_expectations_provider/operators/great_expectations.py", line 30, in <module>
    from great_expectations.checkpoint.types.checkpoint_result import CheckpointResult
ModuleNotFoundError: No module named 'great_expectations.checkpoint.types'
[2025-02-22T08:49:21.811+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/gx.py
[2025-02-22T08:49:21.831+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/gx.py took 2.264 seconds
[2025-02-22T08:49:52.035+0000] {processor.py:157} INFO - Started process (PID=535) to work on /opt/airflow/dags/gx.py
[2025-02-22T08:49:52.036+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/gx.py for tasks to queue
[2025-02-22T08:49:52.038+0000] {logging_mixin.py:151} INFO - [2025-02-22T08:49:52.037+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/gx.py
[2025-02-22T08:49:53.620+0000] {logging_mixin.py:151} INFO - [2025-02-22T08:49:53.619+0000] {warnings.py:109} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:103: UserWarning: You have an incompatible version of 'pyarrow' installed (11.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
  warn_incompatible_dep(
[2025-02-22T08:49:54.156+0000] {logging_mixin.py:151} INFO - [2025-02-22T08:49:54.155+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/gx.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gx.py", line 3, in <module>
    from great_expectations_provider.operators.great_expectations import (
  File "/home/airflow/.local/lib/python3.8/site-packages/great_expectations_provider/operators/great_expectations.py", line 30, in <module>
    from great_expectations.checkpoint.types.checkpoint_result import CheckpointResult
ModuleNotFoundError: No module named 'great_expectations.checkpoint.types'
[2025-02-22T08:49:54.157+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/gx.py
[2025-02-22T08:49:54.180+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/gx.py took 2.151 seconds
[2025-02-22T08:50:24.215+0000] {processor.py:157} INFO - Started process (PID=556) to work on /opt/airflow/dags/gx.py
[2025-02-22T08:50:24.216+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/gx.py for tasks to queue
[2025-02-22T08:50:24.219+0000] {logging_mixin.py:151} INFO - [2025-02-22T08:50:24.218+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/gx.py
[2025-02-22T08:50:25.969+0000] {logging_mixin.py:151} INFO - [2025-02-22T08:50:25.969+0000] {warnings.py:109} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:103: UserWarning: You have an incompatible version of 'pyarrow' installed (11.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
  warn_incompatible_dep(
[2025-02-22T08:50:26.498+0000] {logging_mixin.py:151} INFO - [2025-02-22T08:50:26.497+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/gx.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gx.py", line 3, in <module>
    from great_expectations_provider.operators.great_expectations import (
  File "/home/airflow/.local/lib/python3.8/site-packages/great_expectations_provider/operators/great_expectations.py", line 30, in <module>
    from great_expectations.checkpoint.types.checkpoint_result import CheckpointResult
ModuleNotFoundError: No module named 'great_expectations.checkpoint.types'
[2025-02-22T08:50:26.499+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/gx.py
[2025-02-22T08:50:26.515+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/gx.py took 2.302 seconds
[2025-02-22T08:50:56.668+0000] {processor.py:157} INFO - Started process (PID=577) to work on /opt/airflow/dags/gx.py
[2025-02-22T08:50:56.669+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/gx.py for tasks to queue
[2025-02-22T08:50:56.671+0000] {logging_mixin.py:151} INFO - [2025-02-22T08:50:56.671+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/gx.py
[2025-02-22T08:50:58.363+0000] {logging_mixin.py:151} INFO - [2025-02-22T08:50:58.363+0000] {warnings.py:109} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:103: UserWarning: You have an incompatible version of 'pyarrow' installed (11.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
  warn_incompatible_dep(
[2025-02-22T08:50:58.924+0000] {logging_mixin.py:151} INFO - [2025-02-22T08:50:58.923+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/gx.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gx.py", line 3, in <module>
    from great_expectations_provider.operators.great_expectations import (
  File "/home/airflow/.local/lib/python3.8/site-packages/great_expectations_provider/operators/great_expectations.py", line 30, in <module>
    from great_expectations.checkpoint.types.checkpoint_result import CheckpointResult
ModuleNotFoundError: No module named 'great_expectations.checkpoint.types'
[2025-02-22T08:50:58.924+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/gx.py
[2025-02-22T08:50:58.946+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/gx.py took 2.281 seconds
[2025-02-22T08:51:29.113+0000] {processor.py:157} INFO - Started process (PID=598) to work on /opt/airflow/dags/gx.py
[2025-02-22T08:51:29.114+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/gx.py for tasks to queue
[2025-02-22T08:51:29.117+0000] {logging_mixin.py:151} INFO - [2025-02-22T08:51:29.116+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/gx.py
[2025-02-22T08:51:30.848+0000] {logging_mixin.py:151} INFO - [2025-02-22T08:51:30.848+0000] {warnings.py:109} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:103: UserWarning: You have an incompatible version of 'pyarrow' installed (11.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
  warn_incompatible_dep(
[2025-02-22T08:51:31.409+0000] {logging_mixin.py:151} INFO - [2025-02-22T08:51:31.408+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/gx.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gx.py", line 3, in <module>
    from great_expectations_provider.operators.great_expectations import (
  File "/home/airflow/.local/lib/python3.8/site-packages/great_expectations_provider/operators/great_expectations.py", line 30, in <module>
    from great_expectations.checkpoint.types.checkpoint_result import CheckpointResult
ModuleNotFoundError: No module named 'great_expectations.checkpoint.types'
[2025-02-22T08:51:31.410+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/gx.py
[2025-02-22T08:51:31.431+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/gx.py took 2.321 seconds
[2025-02-22T08:52:01.624+0000] {processor.py:157} INFO - Started process (PID=619) to work on /opt/airflow/dags/gx.py
[2025-02-22T08:52:01.625+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/gx.py for tasks to queue
[2025-02-22T08:52:01.627+0000] {logging_mixin.py:151} INFO - [2025-02-22T08:52:01.627+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/gx.py
[2025-02-22T08:52:03.368+0000] {logging_mixin.py:151} INFO - [2025-02-22T08:52:03.367+0000] {warnings.py:109} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:103: UserWarning: You have an incompatible version of 'pyarrow' installed (11.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
  warn_incompatible_dep(
[2025-02-22T08:52:03.921+0000] {logging_mixin.py:151} INFO - [2025-02-22T08:52:03.920+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/gx.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gx.py", line 3, in <module>
    from great_expectations_provider.operators.great_expectations import (
  File "/home/airflow/.local/lib/python3.8/site-packages/great_expectations_provider/operators/great_expectations.py", line 30, in <module>
    from great_expectations.checkpoint.types.checkpoint_result import CheckpointResult
ModuleNotFoundError: No module named 'great_expectations.checkpoint.types'
[2025-02-22T08:52:03.921+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/gx.py
[2025-02-22T08:52:03.933+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/gx.py took 2.312 seconds
[2025-02-22T08:52:34.134+0000] {processor.py:157} INFO - Started process (PID=640) to work on /opt/airflow/dags/gx.py
[2025-02-22T08:52:34.135+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/gx.py for tasks to queue
[2025-02-22T08:52:34.138+0000] {logging_mixin.py:151} INFO - [2025-02-22T08:52:34.137+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/gx.py
[2025-02-22T08:52:35.753+0000] {logging_mixin.py:151} INFO - [2025-02-22T08:52:35.752+0000] {warnings.py:109} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:103: UserWarning: You have an incompatible version of 'pyarrow' installed (11.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
  warn_incompatible_dep(
[2025-02-22T08:52:36.285+0000] {logging_mixin.py:151} INFO - [2025-02-22T08:52:36.284+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/gx.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gx.py", line 3, in <module>
    from great_expectations_provider.operators.great_expectations import (
  File "/home/airflow/.local/lib/python3.8/site-packages/great_expectations_provider/operators/great_expectations.py", line 30, in <module>
    from great_expectations.checkpoint.types.checkpoint_result import CheckpointResult
ModuleNotFoundError: No module named 'great_expectations.checkpoint.types'
[2025-02-22T08:52:36.286+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/gx.py
[2025-02-22T08:52:36.306+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/gx.py took 2.174 seconds
[2025-02-22T08:53:06.466+0000] {processor.py:157} INFO - Started process (PID=661) to work on /opt/airflow/dags/gx.py
[2025-02-22T08:53:06.467+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/gx.py for tasks to queue
[2025-02-22T08:53:06.479+0000] {logging_mixin.py:151} INFO - [2025-02-22T08:53:06.478+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/gx.py
[2025-02-22T08:53:08.095+0000] {logging_mixin.py:151} INFO - [2025-02-22T08:53:08.094+0000] {warnings.py:109} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:103: UserWarning: You have an incompatible version of 'pyarrow' installed (11.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
  warn_incompatible_dep(
[2025-02-22T08:53:08.629+0000] {logging_mixin.py:151} INFO - [2025-02-22T08:53:08.628+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/gx.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gx.py", line 3, in <module>
    from great_expectations_provider.operators.great_expectations import (
  File "/home/airflow/.local/lib/python3.8/site-packages/great_expectations_provider/operators/great_expectations.py", line 30, in <module>
    from great_expectations.checkpoint.types.checkpoint_result import CheckpointResult
ModuleNotFoundError: No module named 'great_expectations.checkpoint.types'
[2025-02-22T08:53:08.630+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/gx.py
[2025-02-22T08:53:08.652+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/gx.py took 2.188 seconds
[2025-02-22T08:53:38.842+0000] {processor.py:157} INFO - Started process (PID=682) to work on /opt/airflow/dags/gx.py
[2025-02-22T08:53:38.843+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/gx.py for tasks to queue
[2025-02-22T08:53:38.855+0000] {logging_mixin.py:151} INFO - [2025-02-22T08:53:38.854+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/gx.py
[2025-02-22T08:53:40.683+0000] {logging_mixin.py:151} INFO - [2025-02-22T08:53:40.682+0000] {warnings.py:109} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:103: UserWarning: You have an incompatible version of 'pyarrow' installed (11.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
  warn_incompatible_dep(
[2025-02-22T08:53:41.258+0000] {logging_mixin.py:151} INFO - [2025-02-22T08:53:41.257+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/gx.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gx.py", line 3, in <module>
    from great_expectations_provider.operators.great_expectations import (
  File "/home/airflow/.local/lib/python3.8/site-packages/great_expectations_provider/operators/great_expectations.py", line 30, in <module>
    from great_expectations.checkpoint.types.checkpoint_result import CheckpointResult
ModuleNotFoundError: No module named 'great_expectations.checkpoint.types'
[2025-02-22T08:53:41.259+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/gx.py
[2025-02-22T08:53:41.281+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/gx.py took 2.449 seconds
[2025-02-22T08:54:11.460+0000] {processor.py:157} INFO - Started process (PID=703) to work on /opt/airflow/dags/gx.py
[2025-02-22T08:54:11.461+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/gx.py for tasks to queue
[2025-02-22T08:54:11.463+0000] {logging_mixin.py:151} INFO - [2025-02-22T08:54:11.463+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/gx.py
[2025-02-22T08:54:13.353+0000] {logging_mixin.py:151} INFO - [2025-02-22T08:54:13.352+0000] {warnings.py:109} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:103: UserWarning: You have an incompatible version of 'pyarrow' installed (11.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
  warn_incompatible_dep(
[2025-02-22T08:54:13.973+0000] {logging_mixin.py:151} INFO - [2025-02-22T08:54:13.972+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/gx.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gx.py", line 3, in <module>
    from great_expectations_provider.operators.great_expectations import (
  File "/home/airflow/.local/lib/python3.8/site-packages/great_expectations_provider/operators/great_expectations.py", line 30, in <module>
    from great_expectations.checkpoint.types.checkpoint_result import CheckpointResult
ModuleNotFoundError: No module named 'great_expectations.checkpoint.types'
[2025-02-22T08:54:13.973+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/gx.py
[2025-02-22T08:54:13.995+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/gx.py took 2.539 seconds
[2025-02-22T08:54:44.166+0000] {processor.py:157} INFO - Started process (PID=724) to work on /opt/airflow/dags/gx.py
[2025-02-22T08:54:44.167+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/gx.py for tasks to queue
[2025-02-22T08:54:44.169+0000] {logging_mixin.py:151} INFO - [2025-02-22T08:54:44.168+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/gx.py
[2025-02-22T08:54:45.904+0000] {logging_mixin.py:151} INFO - [2025-02-22T08:54:45.904+0000] {warnings.py:109} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:103: UserWarning: You have an incompatible version of 'pyarrow' installed (11.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
  warn_incompatible_dep(
[2025-02-22T08:54:46.431+0000] {logging_mixin.py:151} INFO - [2025-02-22T08:54:46.430+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/gx.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gx.py", line 3, in <module>
    from great_expectations_provider.operators.great_expectations import (
  File "/home/airflow/.local/lib/python3.8/site-packages/great_expectations_provider/operators/great_expectations.py", line 30, in <module>
    from great_expectations.checkpoint.types.checkpoint_result import CheckpointResult
ModuleNotFoundError: No module named 'great_expectations.checkpoint.types'
[2025-02-22T08:54:46.431+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/gx.py
[2025-02-22T08:54:46.451+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/gx.py took 2.289 seconds
[2025-02-22T08:55:16.648+0000] {processor.py:157} INFO - Started process (PID=752) to work on /opt/airflow/dags/gx.py
[2025-02-22T08:55:16.658+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/gx.py for tasks to queue
[2025-02-22T08:55:16.660+0000] {logging_mixin.py:151} INFO - [2025-02-22T08:55:16.660+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/gx.py
[2025-02-22T08:55:18.359+0000] {logging_mixin.py:151} INFO - [2025-02-22T08:55:18.357+0000] {warnings.py:109} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:103: UserWarning: You have an incompatible version of 'pyarrow' installed (11.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
  warn_incompatible_dep(
[2025-02-22T08:55:18.928+0000] {logging_mixin.py:151} INFO - [2025-02-22T08:55:18.927+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/gx.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gx.py", line 3, in <module>
    from great_expectations_provider.operators.great_expectations import (
  File "/home/airflow/.local/lib/python3.8/site-packages/great_expectations_provider/operators/great_expectations.py", line 30, in <module>
    from great_expectations.checkpoint.types.checkpoint_result import CheckpointResult
ModuleNotFoundError: No module named 'great_expectations.checkpoint.types'
[2025-02-22T08:55:18.928+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/gx.py
[2025-02-22T08:55:18.952+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/gx.py took 2.307 seconds
[2025-02-22T08:55:49.140+0000] {processor.py:157} INFO - Started process (PID=773) to work on /opt/airflow/dags/gx.py
[2025-02-22T08:55:49.141+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/gx.py for tasks to queue
[2025-02-22T08:55:49.144+0000] {logging_mixin.py:151} INFO - [2025-02-22T08:55:49.143+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/gx.py
[2025-02-22T08:55:50.787+0000] {logging_mixin.py:151} INFO - [2025-02-22T08:55:50.786+0000] {warnings.py:109} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:103: UserWarning: You have an incompatible version of 'pyarrow' installed (11.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
  warn_incompatible_dep(
[2025-02-22T08:55:51.317+0000] {logging_mixin.py:151} INFO - [2025-02-22T08:55:51.316+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/gx.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gx.py", line 3, in <module>
    from great_expectations_provider.operators.great_expectations import (
  File "/home/airflow/.local/lib/python3.8/site-packages/great_expectations_provider/operators/great_expectations.py", line 30, in <module>
    from great_expectations.checkpoint.types.checkpoint_result import CheckpointResult
ModuleNotFoundError: No module named 'great_expectations.checkpoint.types'
[2025-02-22T08:55:51.318+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/gx.py
[2025-02-22T08:55:51.342+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/gx.py took 2.204 seconds
[2025-02-22T08:56:21.505+0000] {processor.py:157} INFO - Started process (PID=794) to work on /opt/airflow/dags/gx.py
[2025-02-22T08:56:21.506+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/gx.py for tasks to queue
[2025-02-22T08:56:21.509+0000] {logging_mixin.py:151} INFO - [2025-02-22T08:56:21.508+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/gx.py
[2025-02-22T08:56:23.288+0000] {logging_mixin.py:151} INFO - [2025-02-22T08:56:23.287+0000] {warnings.py:109} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:103: UserWarning: You have an incompatible version of 'pyarrow' installed (11.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
  warn_incompatible_dep(
[2025-02-22T08:56:23.837+0000] {logging_mixin.py:151} INFO - [2025-02-22T08:56:23.836+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/gx.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gx.py", line 3, in <module>
    from great_expectations_provider.operators.great_expectations import (
  File "/home/airflow/.local/lib/python3.8/site-packages/great_expectations_provider/operators/great_expectations.py", line 30, in <module>
    from great_expectations.checkpoint.types.checkpoint_result import CheckpointResult
ModuleNotFoundError: No module named 'great_expectations.checkpoint.types'
[2025-02-22T08:56:23.838+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/gx.py
[2025-02-22T08:56:23.849+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/gx.py took 2.347 seconds
[2025-02-22T08:56:54.030+0000] {processor.py:157} INFO - Started process (PID=815) to work on /opt/airflow/dags/gx.py
[2025-02-22T08:56:54.031+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/gx.py for tasks to queue
[2025-02-22T08:56:54.034+0000] {logging_mixin.py:151} INFO - [2025-02-22T08:56:54.033+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/gx.py
[2025-02-22T08:56:55.679+0000] {logging_mixin.py:151} INFO - [2025-02-22T08:56:55.679+0000] {warnings.py:109} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:103: UserWarning: You have an incompatible version of 'pyarrow' installed (11.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
  warn_incompatible_dep(
[2025-02-22T08:56:56.203+0000] {logging_mixin.py:151} INFO - [2025-02-22T08:56:56.202+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/gx.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gx.py", line 3, in <module>
    from great_expectations_provider.operators.great_expectations import (
  File "/home/airflow/.local/lib/python3.8/site-packages/great_expectations_provider/operators/great_expectations.py", line 30, in <module>
    from great_expectations.checkpoint.types.checkpoint_result import CheckpointResult
ModuleNotFoundError: No module named 'great_expectations.checkpoint.types'
[2025-02-22T08:56:56.204+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/gx.py
[2025-02-22T08:56:56.216+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/gx.py took 2.192 seconds
[2025-02-22T08:57:26.378+0000] {processor.py:157} INFO - Started process (PID=836) to work on /opt/airflow/dags/gx.py
[2025-02-22T08:57:26.379+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/gx.py for tasks to queue
[2025-02-22T08:57:26.383+0000] {logging_mixin.py:151} INFO - [2025-02-22T08:57:26.382+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/gx.py
[2025-02-22T08:57:28.182+0000] {logging_mixin.py:151} INFO - [2025-02-22T08:57:28.181+0000] {warnings.py:109} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:103: UserWarning: You have an incompatible version of 'pyarrow' installed (11.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
  warn_incompatible_dep(
[2025-02-22T08:57:28.750+0000] {logging_mixin.py:151} INFO - [2025-02-22T08:57:28.749+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/gx.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gx.py", line 3, in <module>
    from great_expectations_provider.operators.great_expectations import (
  File "/home/airflow/.local/lib/python3.8/site-packages/great_expectations_provider/operators/great_expectations.py", line 30, in <module>
    from great_expectations.checkpoint.types.checkpoint_result import CheckpointResult
ModuleNotFoundError: No module named 'great_expectations.checkpoint.types'
[2025-02-22T08:57:28.750+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/gx.py
[2025-02-22T08:57:28.771+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/gx.py took 2.396 seconds
[2025-02-22T08:57:58.950+0000] {processor.py:157} INFO - Started process (PID=857) to work on /opt/airflow/dags/gx.py
[2025-02-22T08:57:58.952+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/gx.py for tasks to queue
[2025-02-22T08:57:58.956+0000] {logging_mixin.py:151} INFO - [2025-02-22T08:57:58.955+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/gx.py
[2025-02-22T08:58:00.695+0000] {logging_mixin.py:151} INFO - [2025-02-22T08:58:00.694+0000] {warnings.py:109} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:103: UserWarning: You have an incompatible version of 'pyarrow' installed (11.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
  warn_incompatible_dep(
[2025-02-22T08:58:01.244+0000] {logging_mixin.py:151} INFO - [2025-02-22T08:58:01.243+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/gx.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gx.py", line 3, in <module>
    from great_expectations_provider.operators.great_expectations import (
  File "/home/airflow/.local/lib/python3.8/site-packages/great_expectations_provider/operators/great_expectations.py", line 30, in <module>
    from great_expectations.checkpoint.types.checkpoint_result import CheckpointResult
ModuleNotFoundError: No module named 'great_expectations.checkpoint.types'
[2025-02-22T08:58:01.245+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/gx.py
[2025-02-22T08:58:01.264+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/gx.py took 2.322 seconds
[2025-02-22T08:58:31.447+0000] {processor.py:157} INFO - Started process (PID=878) to work on /opt/airflow/dags/gx.py
[2025-02-22T08:58:31.447+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/gx.py for tasks to queue
[2025-02-22T08:58:31.450+0000] {logging_mixin.py:151} INFO - [2025-02-22T08:58:31.450+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/gx.py
[2025-02-22T08:58:33.243+0000] {logging_mixin.py:151} INFO - [2025-02-22T08:58:33.243+0000] {warnings.py:109} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:103: UserWarning: You have an incompatible version of 'pyarrow' installed (11.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
  warn_incompatible_dep(
[2025-02-22T08:58:33.822+0000] {logging_mixin.py:151} INFO - [2025-02-22T08:58:33.821+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/gx.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gx.py", line 3, in <module>
    from great_expectations_provider.operators.great_expectations import (
  File "/home/airflow/.local/lib/python3.8/site-packages/great_expectations_provider/operators/great_expectations.py", line 30, in <module>
    from great_expectations.checkpoint.types.checkpoint_result import CheckpointResult
ModuleNotFoundError: No module named 'great_expectations.checkpoint.types'
[2025-02-22T08:58:33.823+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/gx.py
[2025-02-22T08:58:33.838+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/gx.py took 2.396 seconds
[2025-02-22T08:59:04.004+0000] {processor.py:157} INFO - Started process (PID=899) to work on /opt/airflow/dags/gx.py
[2025-02-22T08:59:04.005+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/gx.py for tasks to queue
[2025-02-22T08:59:04.008+0000] {logging_mixin.py:151} INFO - [2025-02-22T08:59:04.007+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/gx.py
[2025-02-22T08:59:05.696+0000] {logging_mixin.py:151} INFO - [2025-02-22T08:59:05.695+0000] {warnings.py:109} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:103: UserWarning: You have an incompatible version of 'pyarrow' installed (11.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
  warn_incompatible_dep(
[2025-02-22T08:59:06.279+0000] {logging_mixin.py:151} INFO - [2025-02-22T08:59:06.278+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/gx.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gx.py", line 3, in <module>
    from great_expectations_provider.operators.great_expectations import (
  File "/home/airflow/.local/lib/python3.8/site-packages/great_expectations_provider/operators/great_expectations.py", line 30, in <module>
    from great_expectations.checkpoint.types.checkpoint_result import CheckpointResult
ModuleNotFoundError: No module named 'great_expectations.checkpoint.types'
[2025-02-22T08:59:06.279+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/gx.py
[2025-02-22T08:59:06.302+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/gx.py took 2.304 seconds
[2025-02-22T08:59:36.452+0000] {processor.py:157} INFO - Started process (PID=920) to work on /opt/airflow/dags/gx.py
[2025-02-22T08:59:36.453+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/gx.py for tasks to queue
[2025-02-22T08:59:36.455+0000] {logging_mixin.py:151} INFO - [2025-02-22T08:59:36.455+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/gx.py
[2025-02-22T08:59:38.094+0000] {logging_mixin.py:151} INFO - [2025-02-22T08:59:38.093+0000] {warnings.py:109} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:103: UserWarning: You have an incompatible version of 'pyarrow' installed (11.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
  warn_incompatible_dep(
[2025-02-22T08:59:38.621+0000] {logging_mixin.py:151} INFO - [2025-02-22T08:59:38.619+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/gx.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gx.py", line 3, in <module>
    from great_expectations_provider.operators.great_expectations import (
  File "/home/airflow/.local/lib/python3.8/site-packages/great_expectations_provider/operators/great_expectations.py", line 30, in <module>
    from great_expectations.checkpoint.types.checkpoint_result import CheckpointResult
ModuleNotFoundError: No module named 'great_expectations.checkpoint.types'
[2025-02-22T08:59:38.621+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/gx.py
[2025-02-22T08:59:38.643+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/gx.py took 2.193 seconds
[2025-02-22T09:00:08.829+0000] {processor.py:157} INFO - Started process (PID=941) to work on /opt/airflow/dags/gx.py
[2025-02-22T09:00:08.830+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/gx.py for tasks to queue
[2025-02-22T09:00:08.832+0000] {logging_mixin.py:151} INFO - [2025-02-22T09:00:08.832+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/gx.py
[2025-02-22T09:00:10.519+0000] {logging_mixin.py:151} INFO - [2025-02-22T09:00:10.518+0000] {warnings.py:109} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:103: UserWarning: You have an incompatible version of 'pyarrow' installed (11.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
  warn_incompatible_dep(
[2025-02-22T09:00:11.051+0000] {logging_mixin.py:151} INFO - [2025-02-22T09:00:11.050+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/gx.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gx.py", line 3, in <module>
    from great_expectations_provider.operators.great_expectations import (
  File "/home/airflow/.local/lib/python3.8/site-packages/great_expectations_provider/operators/great_expectations.py", line 30, in <module>
    from great_expectations.checkpoint.types.checkpoint_result import CheckpointResult
ModuleNotFoundError: No module named 'great_expectations.checkpoint.types'
[2025-02-22T09:00:11.052+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/gx.py
[2025-02-22T09:00:11.064+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/gx.py took 2.238 seconds
[2025-02-22T09:00:41.228+0000] {processor.py:157} INFO - Started process (PID=962) to work on /opt/airflow/dags/gx.py
[2025-02-22T09:00:41.229+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/gx.py for tasks to queue
[2025-02-22T09:00:41.231+0000] {logging_mixin.py:151} INFO - [2025-02-22T09:00:41.231+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/gx.py
[2025-02-22T09:00:42.789+0000] {logging_mixin.py:151} INFO - [2025-02-22T09:00:42.788+0000] {warnings.py:109} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:103: UserWarning: You have an incompatible version of 'pyarrow' installed (11.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
  warn_incompatible_dep(
[2025-02-22T09:00:43.346+0000] {logging_mixin.py:151} INFO - [2025-02-22T09:00:43.345+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/gx.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gx.py", line 3, in <module>
    from great_expectations_provider.operators.great_expectations import (
  File "/home/airflow/.local/lib/python3.8/site-packages/great_expectations_provider/operators/great_expectations.py", line 30, in <module>
    from great_expectations.checkpoint.types.checkpoint_result import CheckpointResult
ModuleNotFoundError: No module named 'great_expectations.checkpoint.types'
[2025-02-22T09:00:43.347+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/gx.py
[2025-02-22T09:00:43.367+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/gx.py took 2.142 seconds
[2025-02-22T09:01:13.400+0000] {processor.py:157} INFO - Started process (PID=983) to work on /opt/airflow/dags/gx.py
[2025-02-22T09:01:13.401+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/gx.py for tasks to queue
[2025-02-22T09:01:13.403+0000] {logging_mixin.py:151} INFO - [2025-02-22T09:01:13.403+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/gx.py
[2025-02-22T09:01:14.978+0000] {logging_mixin.py:151} INFO - [2025-02-22T09:01:14.977+0000] {warnings.py:109} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:103: UserWarning: You have an incompatible version of 'pyarrow' installed (11.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
  warn_incompatible_dep(
[2025-02-22T09:01:15.502+0000] {logging_mixin.py:151} INFO - [2025-02-22T09:01:15.501+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/gx.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gx.py", line 3, in <module>
    from great_expectations_provider.operators.great_expectations import (
  File "/home/airflow/.local/lib/python3.8/site-packages/great_expectations_provider/operators/great_expectations.py", line 30, in <module>
    from great_expectations.checkpoint.types.checkpoint_result import CheckpointResult
ModuleNotFoundError: No module named 'great_expectations.checkpoint.types'
[2025-02-22T09:01:15.503+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/gx.py
[2025-02-22T09:01:15.515+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/gx.py took 2.118 seconds
[2025-02-22T09:01:45.694+0000] {processor.py:157} INFO - Started process (PID=1004) to work on /opt/airflow/dags/gx.py
[2025-02-22T09:01:45.695+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/gx.py for tasks to queue
[2025-02-22T09:01:45.697+0000] {logging_mixin.py:151} INFO - [2025-02-22T09:01:45.697+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/gx.py
[2025-02-22T09:01:47.386+0000] {logging_mixin.py:151} INFO - [2025-02-22T09:01:47.385+0000] {warnings.py:109} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:103: UserWarning: You have an incompatible version of 'pyarrow' installed (11.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
  warn_incompatible_dep(
[2025-02-22T09:01:47.941+0000] {logging_mixin.py:151} INFO - [2025-02-22T09:01:47.940+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/gx.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gx.py", line 3, in <module>
    from great_expectations_provider.operators.great_expectations import (
  File "/home/airflow/.local/lib/python3.8/site-packages/great_expectations_provider/operators/great_expectations.py", line 30, in <module>
    from great_expectations.checkpoint.types.checkpoint_result import CheckpointResult
ModuleNotFoundError: No module named 'great_expectations.checkpoint.types'
[2025-02-22T09:01:47.941+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/gx.py
[2025-02-22T09:01:47.962+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/gx.py took 2.270 seconds
[2025-02-22T09:02:18.144+0000] {processor.py:157} INFO - Started process (PID=1032) to work on /opt/airflow/dags/gx.py
[2025-02-22T09:02:18.145+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/gx.py for tasks to queue
[2025-02-22T09:02:18.148+0000] {logging_mixin.py:151} INFO - [2025-02-22T09:02:18.147+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/gx.py
[2025-02-22T09:02:19.798+0000] {logging_mixin.py:151} INFO - [2025-02-22T09:02:19.797+0000] {warnings.py:109} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:103: UserWarning: You have an incompatible version of 'pyarrow' installed (11.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
  warn_incompatible_dep(
[2025-02-22T09:02:20.382+0000] {logging_mixin.py:151} INFO - [2025-02-22T09:02:20.380+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/gx.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gx.py", line 3, in <module>
    from great_expectations_provider.operators.great_expectations import (
  File "/home/airflow/.local/lib/python3.8/site-packages/great_expectations_provider/operators/great_expectations.py", line 30, in <module>
    from great_expectations.checkpoint.types.checkpoint_result import CheckpointResult
ModuleNotFoundError: No module named 'great_expectations.checkpoint.types'
[2025-02-22T09:02:20.382+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/gx.py
[2025-02-22T09:02:20.402+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/gx.py took 2.261 seconds
[2025-02-22T09:02:50.587+0000] {processor.py:157} INFO - Started process (PID=1053) to work on /opt/airflow/dags/gx.py
[2025-02-22T09:02:50.588+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/gx.py for tasks to queue
[2025-02-22T09:02:50.590+0000] {logging_mixin.py:151} INFO - [2025-02-22T09:02:50.589+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/gx.py
[2025-02-22T09:02:52.353+0000] {logging_mixin.py:151} INFO - [2025-02-22T09:02:52.352+0000] {warnings.py:109} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:103: UserWarning: You have an incompatible version of 'pyarrow' installed (11.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
  warn_incompatible_dep(
[2025-02-22T09:02:52.909+0000] {logging_mixin.py:151} INFO - [2025-02-22T09:02:52.908+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/gx.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gx.py", line 3, in <module>
    from great_expectations_provider.operators.great_expectations import (
  File "/home/airflow/.local/lib/python3.8/site-packages/great_expectations_provider/operators/great_expectations.py", line 30, in <module>
    from great_expectations.checkpoint.types.checkpoint_result import CheckpointResult
ModuleNotFoundError: No module named 'great_expectations.checkpoint.types'
[2025-02-22T09:02:52.910+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/gx.py
[2025-02-22T09:02:52.931+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/gx.py took 2.346 seconds
[2025-02-22T09:03:23.106+0000] {processor.py:157} INFO - Started process (PID=1074) to work on /opt/airflow/dags/gx.py
[2025-02-22T09:03:23.107+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/gx.py for tasks to queue
[2025-02-22T09:03:23.109+0000] {logging_mixin.py:151} INFO - [2025-02-22T09:03:23.109+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/gx.py
[2025-02-22T09:03:24.890+0000] {logging_mixin.py:151} INFO - [2025-02-22T09:03:24.889+0000] {warnings.py:109} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:103: UserWarning: You have an incompatible version of 'pyarrow' installed (11.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
  warn_incompatible_dep(
[2025-02-22T09:03:25.449+0000] {logging_mixin.py:151} INFO - [2025-02-22T09:03:25.448+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/gx.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gx.py", line 3, in <module>
    from great_expectations_provider.operators.great_expectations import (
  File "/home/airflow/.local/lib/python3.8/site-packages/great_expectations_provider/operators/great_expectations.py", line 30, in <module>
    from great_expectations.checkpoint.types.checkpoint_result import CheckpointResult
ModuleNotFoundError: No module named 'great_expectations.checkpoint.types'
[2025-02-22T09:03:25.449+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/gx.py
[2025-02-22T09:03:25.473+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/gx.py took 2.370 seconds
[2025-02-22T09:03:55.655+0000] {processor.py:157} INFO - Started process (PID=1095) to work on /opt/airflow/dags/gx.py
[2025-02-22T09:03:55.657+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/gx.py for tasks to queue
[2025-02-22T09:03:55.660+0000] {logging_mixin.py:151} INFO - [2025-02-22T09:03:55.660+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/gx.py
[2025-02-22T09:03:57.419+0000] {logging_mixin.py:151} INFO - [2025-02-22T09:03:57.419+0000] {warnings.py:109} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:103: UserWarning: You have an incompatible version of 'pyarrow' installed (11.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
  warn_incompatible_dep(
[2025-02-22T09:03:57.982+0000] {logging_mixin.py:151} INFO - [2025-02-22T09:03:57.981+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/gx.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gx.py", line 3, in <module>
    from great_expectations_provider.operators.great_expectations import (
  File "/home/airflow/.local/lib/python3.8/site-packages/great_expectations_provider/operators/great_expectations.py", line 30, in <module>
    from great_expectations.checkpoint.types.checkpoint_result import CheckpointResult
ModuleNotFoundError: No module named 'great_expectations.checkpoint.types'
[2025-02-22T09:03:57.983+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/gx.py
[2025-02-22T09:03:57.997+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/gx.py took 2.345 seconds
[2025-02-22T09:04:28.187+0000] {processor.py:157} INFO - Started process (PID=1116) to work on /opt/airflow/dags/gx.py
[2025-02-22T09:04:28.188+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/gx.py for tasks to queue
[2025-02-22T09:04:28.190+0000] {logging_mixin.py:151} INFO - [2025-02-22T09:04:28.190+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/gx.py
[2025-02-22T09:04:29.984+0000] {logging_mixin.py:151} INFO - [2025-02-22T09:04:29.983+0000] {warnings.py:109} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:103: UserWarning: You have an incompatible version of 'pyarrow' installed (11.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
  warn_incompatible_dep(
[2025-02-22T09:04:30.542+0000] {logging_mixin.py:151} INFO - [2025-02-22T09:04:30.541+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/gx.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gx.py", line 3, in <module>
    from great_expectations_provider.operators.great_expectations import (
  File "/home/airflow/.local/lib/python3.8/site-packages/great_expectations_provider/operators/great_expectations.py", line 30, in <module>
    from great_expectations.checkpoint.types.checkpoint_result import CheckpointResult
ModuleNotFoundError: No module named 'great_expectations.checkpoint.types'
[2025-02-22T09:04:30.543+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/gx.py
[2025-02-22T09:04:30.564+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/gx.py took 2.383 seconds
[2025-02-22T09:05:00.735+0000] {processor.py:157} INFO - Started process (PID=1137) to work on /opt/airflow/dags/gx.py
[2025-02-22T09:05:00.736+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/gx.py for tasks to queue
[2025-02-22T09:05:00.738+0000] {logging_mixin.py:151} INFO - [2025-02-22T09:05:00.738+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/gx.py
[2025-02-22T09:05:02.476+0000] {logging_mixin.py:151} INFO - [2025-02-22T09:05:02.476+0000] {warnings.py:109} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:103: UserWarning: You have an incompatible version of 'pyarrow' installed (11.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
  warn_incompatible_dep(
[2025-02-22T09:05:03.102+0000] {logging_mixin.py:151} INFO - [2025-02-22T09:05:03.100+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/gx.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gx.py", line 3, in <module>
    from great_expectations_provider.operators.great_expectations import (
  File "/home/airflow/.local/lib/python3.8/site-packages/great_expectations_provider/operators/great_expectations.py", line 30, in <module>
    from great_expectations.checkpoint.types.checkpoint_result import CheckpointResult
ModuleNotFoundError: No module named 'great_expectations.checkpoint.types'
[2025-02-22T09:05:03.103+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/gx.py
[2025-02-22T09:05:03.119+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/gx.py took 2.386 seconds
[2025-02-22T09:05:33.281+0000] {processor.py:157} INFO - Started process (PID=1158) to work on /opt/airflow/dags/gx.py
[2025-02-22T09:05:33.282+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/gx.py for tasks to queue
[2025-02-22T09:05:33.285+0000] {logging_mixin.py:151} INFO - [2025-02-22T09:05:33.284+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/gx.py
[2025-02-22T09:05:35.473+0000] {logging_mixin.py:151} INFO - [2025-02-22T09:05:35.472+0000] {warnings.py:109} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:103: UserWarning: You have an incompatible version of 'pyarrow' installed (11.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
  warn_incompatible_dep(
[2025-02-22T09:05:36.034+0000] {logging_mixin.py:151} INFO - [2025-02-22T09:05:36.033+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/gx.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gx.py", line 3, in <module>
    from great_expectations_provider.operators.great_expectations import (
  File "/home/airflow/.local/lib/python3.8/site-packages/great_expectations_provider/operators/great_expectations.py", line 30, in <module>
    from great_expectations.checkpoint.types.checkpoint_result import CheckpointResult
ModuleNotFoundError: No module named 'great_expectations.checkpoint.types'
[2025-02-22T09:05:36.035+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/gx.py
[2025-02-22T09:05:36.060+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/gx.py took 2.781 seconds
[2025-02-22T09:06:06.224+0000] {processor.py:157} INFO - Started process (PID=1179) to work on /opt/airflow/dags/gx.py
[2025-02-22T09:06:06.225+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/gx.py for tasks to queue
[2025-02-22T09:06:06.227+0000] {logging_mixin.py:151} INFO - [2025-02-22T09:06:06.227+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/gx.py
[2025-02-22T09:06:08.017+0000] {logging_mixin.py:151} INFO - [2025-02-22T09:06:08.016+0000] {warnings.py:109} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:103: UserWarning: You have an incompatible version of 'pyarrow' installed (11.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
  warn_incompatible_dep(
[2025-02-22T09:06:08.657+0000] {logging_mixin.py:151} INFO - [2025-02-22T09:06:08.656+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/gx.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gx.py", line 3, in <module>
    from great_expectations_provider.operators.great_expectations import (
  File "/home/airflow/.local/lib/python3.8/site-packages/great_expectations_provider/operators/great_expectations.py", line 30, in <module>
    from great_expectations.checkpoint.types.checkpoint_result import CheckpointResult
ModuleNotFoundError: No module named 'great_expectations.checkpoint.types'
[2025-02-22T09:06:08.658+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/gx.py
[2025-02-22T09:06:08.673+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/gx.py took 2.452 seconds
[2025-02-22T09:06:38.827+0000] {processor.py:157} INFO - Started process (PID=1200) to work on /opt/airflow/dags/gx.py
[2025-02-22T09:06:38.828+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/gx.py for tasks to queue
[2025-02-22T09:06:38.831+0000] {logging_mixin.py:151} INFO - [2025-02-22T09:06:38.831+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/gx.py
[2025-02-22T09:06:40.657+0000] {logging_mixin.py:151} INFO - [2025-02-22T09:06:40.656+0000] {warnings.py:109} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:103: UserWarning: You have an incompatible version of 'pyarrow' installed (11.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
  warn_incompatible_dep(
[2025-02-22T09:06:41.213+0000] {logging_mixin.py:151} INFO - [2025-02-22T09:06:41.211+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/gx.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gx.py", line 3, in <module>
    from great_expectations_provider.operators.great_expectations import (
  File "/home/airflow/.local/lib/python3.8/site-packages/great_expectations_provider/operators/great_expectations.py", line 30, in <module>
    from great_expectations.checkpoint.types.checkpoint_result import CheckpointResult
ModuleNotFoundError: No module named 'great_expectations.checkpoint.types'
[2025-02-22T09:06:41.213+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/gx.py
[2025-02-22T09:06:41.234+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/gx.py took 2.409 seconds
[2025-02-22T09:07:11.400+0000] {processor.py:157} INFO - Started process (PID=1221) to work on /opt/airflow/dags/gx.py
[2025-02-22T09:07:11.401+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/gx.py for tasks to queue
[2025-02-22T09:07:11.404+0000] {logging_mixin.py:151} INFO - [2025-02-22T09:07:11.404+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/gx.py
[2025-02-22T09:07:13.185+0000] {logging_mixin.py:151} INFO - [2025-02-22T09:07:13.184+0000] {warnings.py:109} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:103: UserWarning: You have an incompatible version of 'pyarrow' installed (11.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
  warn_incompatible_dep(
[2025-02-22T09:07:13.710+0000] {logging_mixin.py:151} INFO - [2025-02-22T09:07:13.709+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/gx.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gx.py", line 3, in <module>
    from great_expectations_provider.operators.great_expectations import (
  File "/home/airflow/.local/lib/python3.8/site-packages/great_expectations_provider/operators/great_expectations.py", line 30, in <module>
    from great_expectations.checkpoint.types.checkpoint_result import CheckpointResult
ModuleNotFoundError: No module named 'great_expectations.checkpoint.types'
[2025-02-22T09:07:13.711+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/gx.py
[2025-02-22T09:07:13.723+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/gx.py took 2.326 seconds
[2025-02-22T09:07:43.899+0000] {processor.py:157} INFO - Started process (PID=1242) to work on /opt/airflow/dags/gx.py
[2025-02-22T09:07:43.900+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/gx.py for tasks to queue
[2025-02-22T09:07:43.902+0000] {logging_mixin.py:151} INFO - [2025-02-22T09:07:43.902+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/gx.py
[2025-02-22T09:07:45.674+0000] {logging_mixin.py:151} INFO - [2025-02-22T09:07:45.673+0000] {warnings.py:109} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:103: UserWarning: You have an incompatible version of 'pyarrow' installed (11.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
  warn_incompatible_dep(
[2025-02-22T09:07:46.261+0000] {logging_mixin.py:151} INFO - [2025-02-22T09:07:46.260+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/gx.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gx.py", line 3, in <module>
    from great_expectations_provider.operators.great_expectations import (
  File "/home/airflow/.local/lib/python3.8/site-packages/great_expectations_provider/operators/great_expectations.py", line 30, in <module>
    from great_expectations.checkpoint.types.checkpoint_result import CheckpointResult
ModuleNotFoundError: No module named 'great_expectations.checkpoint.types'
[2025-02-22T09:07:46.262+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/gx.py
[2025-02-22T09:07:46.285+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/gx.py took 2.389 seconds
[2025-02-22T09:08:16.453+0000] {processor.py:157} INFO - Started process (PID=1263) to work on /opt/airflow/dags/gx.py
[2025-02-22T09:08:16.454+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/gx.py for tasks to queue
[2025-02-22T09:08:16.458+0000] {logging_mixin.py:151} INFO - [2025-02-22T09:08:16.457+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/gx.py
[2025-02-22T09:08:18.316+0000] {logging_mixin.py:151} INFO - [2025-02-22T09:08:18.316+0000] {warnings.py:109} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:103: UserWarning: You have an incompatible version of 'pyarrow' installed (11.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
  warn_incompatible_dep(
[2025-02-22T09:08:18.970+0000] {logging_mixin.py:151} INFO - [2025-02-22T09:08:18.968+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/gx.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gx.py", line 3, in <module>
    from great_expectations_provider.operators.great_expectations import (
  File "/home/airflow/.local/lib/python3.8/site-packages/great_expectations_provider/operators/great_expectations.py", line 30, in <module>
    from great_expectations.checkpoint.types.checkpoint_result import CheckpointResult
ModuleNotFoundError: No module named 'great_expectations.checkpoint.types'
[2025-02-22T09:08:18.970+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/gx.py
[2025-02-22T09:08:18.985+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/gx.py took 2.535 seconds
[2025-02-22T09:08:49.152+0000] {processor.py:157} INFO - Started process (PID=1291) to work on /opt/airflow/dags/gx.py
[2025-02-22T09:08:49.153+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/gx.py for tasks to queue
[2025-02-22T09:08:49.156+0000] {logging_mixin.py:151} INFO - [2025-02-22T09:08:49.156+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/gx.py
[2025-02-22T09:08:51.126+0000] {logging_mixin.py:151} INFO - [2025-02-22T09:08:51.125+0000] {warnings.py:109} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:103: UserWarning: You have an incompatible version of 'pyarrow' installed (11.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
  warn_incompatible_dep(
[2025-02-22T09:08:51.702+0000] {logging_mixin.py:151} INFO - [2025-02-22T09:08:51.700+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/gx.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gx.py", line 3, in <module>
    from great_expectations_provider.operators.great_expectations import (
  File "/home/airflow/.local/lib/python3.8/site-packages/great_expectations_provider/operators/great_expectations.py", line 30, in <module>
    from great_expectations.checkpoint.types.checkpoint_result import CheckpointResult
ModuleNotFoundError: No module named 'great_expectations.checkpoint.types'
[2025-02-22T09:08:51.703+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/gx.py
[2025-02-22T09:08:51.715+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/gx.py took 2.567 seconds
[2025-02-22T09:09:21.769+0000] {processor.py:157} INFO - Started process (PID=1312) to work on /opt/airflow/dags/gx.py
[2025-02-22T09:09:21.771+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/gx.py for tasks to queue
[2025-02-22T09:09:21.775+0000] {logging_mixin.py:151} INFO - [2025-02-22T09:09:21.774+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/gx.py
[2025-02-22T09:09:23.597+0000] {logging_mixin.py:151} INFO - [2025-02-22T09:09:23.596+0000] {warnings.py:109} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:103: UserWarning: You have an incompatible version of 'pyarrow' installed (11.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
  warn_incompatible_dep(
[2025-02-22T09:09:24.166+0000] {logging_mixin.py:151} INFO - [2025-02-22T09:09:24.165+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/gx.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gx.py", line 3, in <module>
    from great_expectations_provider.operators.great_expectations import (
  File "/home/airflow/.local/lib/python3.8/site-packages/great_expectations_provider/operators/great_expectations.py", line 30, in <module>
    from great_expectations.checkpoint.types.checkpoint_result import CheckpointResult
ModuleNotFoundError: No module named 'great_expectations.checkpoint.types'
[2025-02-22T09:09:24.167+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/gx.py
[2025-02-22T09:09:24.180+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/gx.py took 2.418 seconds
[2025-02-22T09:09:54.390+0000] {processor.py:157} INFO - Started process (PID=1333) to work on /opt/airflow/dags/gx.py
[2025-02-22T09:09:54.392+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/gx.py for tasks to queue
[2025-02-22T09:09:54.396+0000] {logging_mixin.py:151} INFO - [2025-02-22T09:09:54.395+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/gx.py
[2025-02-22T09:09:56.183+0000] {logging_mixin.py:151} INFO - [2025-02-22T09:09:56.182+0000] {warnings.py:109} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:103: UserWarning: You have an incompatible version of 'pyarrow' installed (11.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
  warn_incompatible_dep(
[2025-02-22T09:09:56.778+0000] {logging_mixin.py:151} INFO - [2025-02-22T09:09:56.777+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/gx.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gx.py", line 3, in <module>
    from great_expectations_provider.operators.great_expectations import (
  File "/home/airflow/.local/lib/python3.8/site-packages/great_expectations_provider/operators/great_expectations.py", line 30, in <module>
    from great_expectations.checkpoint.types.checkpoint_result import CheckpointResult
ModuleNotFoundError: No module named 'great_expectations.checkpoint.types'
[2025-02-22T09:09:56.779+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/gx.py
[2025-02-22T09:09:56.796+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/gx.py took 2.416 seconds
[2025-02-22T09:10:27.029+0000] {processor.py:157} INFO - Started process (PID=1354) to work on /opt/airflow/dags/gx.py
[2025-02-22T09:10:27.029+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/gx.py for tasks to queue
[2025-02-22T09:10:27.032+0000] {logging_mixin.py:151} INFO - [2025-02-22T09:10:27.031+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/gx.py
[2025-02-22T09:10:29.020+0000] {logging_mixin.py:151} INFO - [2025-02-22T09:10:29.019+0000] {warnings.py:109} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:103: UserWarning: You have an incompatible version of 'pyarrow' installed (11.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
  warn_incompatible_dep(
[2025-02-22T09:10:29.593+0000] {logging_mixin.py:151} INFO - [2025-02-22T09:10:29.592+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/gx.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gx.py", line 3, in <module>
    from great_expectations_provider.operators.great_expectations import (
  File "/home/airflow/.local/lib/python3.8/site-packages/great_expectations_provider/operators/great_expectations.py", line 30, in <module>
    from great_expectations.checkpoint.types.checkpoint_result import CheckpointResult
ModuleNotFoundError: No module named 'great_expectations.checkpoint.types'
[2025-02-22T09:10:29.593+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/gx.py
[2025-02-22T09:10:29.614+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/gx.py took 2.589 seconds
[2025-02-22T09:10:59.770+0000] {processor.py:157} INFO - Started process (PID=1375) to work on /opt/airflow/dags/gx.py
[2025-02-22T09:10:59.771+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/gx.py for tasks to queue
[2025-02-22T09:10:59.773+0000] {logging_mixin.py:151} INFO - [2025-02-22T09:10:59.773+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/gx.py
[2025-02-22T09:11:01.518+0000] {logging_mixin.py:151} INFO - [2025-02-22T09:11:01.517+0000] {warnings.py:109} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:103: UserWarning: You have an incompatible version of 'pyarrow' installed (11.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
  warn_incompatible_dep(
[2025-02-22T09:11:02.082+0000] {logging_mixin.py:151} INFO - [2025-02-22T09:11:02.080+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/gx.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gx.py", line 3, in <module>
    from great_expectations_provider.operators.great_expectations import (
  File "/home/airflow/.local/lib/python3.8/site-packages/great_expectations_provider/operators/great_expectations.py", line 30, in <module>
    from great_expectations.checkpoint.types.checkpoint_result import CheckpointResult
ModuleNotFoundError: No module named 'great_expectations.checkpoint.types'
[2025-02-22T09:11:02.082+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/gx.py
[2025-02-22T09:11:02.105+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/gx.py took 2.338 seconds
[2025-02-22T09:11:32.274+0000] {processor.py:157} INFO - Started process (PID=1396) to work on /opt/airflow/dags/gx.py
[2025-02-22T09:11:32.275+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/gx.py for tasks to queue
[2025-02-22T09:11:32.277+0000] {logging_mixin.py:151} INFO - [2025-02-22T09:11:32.277+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/gx.py
[2025-02-22T09:11:34.112+0000] {logging_mixin.py:151} INFO - [2025-02-22T09:11:34.112+0000] {warnings.py:109} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:103: UserWarning: You have an incompatible version of 'pyarrow' installed (11.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
  warn_incompatible_dep(
[2025-02-22T09:11:34.675+0000] {logging_mixin.py:151} INFO - [2025-02-22T09:11:34.674+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/gx.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gx.py", line 3, in <module>
    from great_expectations_provider.operators.great_expectations import (
  File "/home/airflow/.local/lib/python3.8/site-packages/great_expectations_provider/operators/great_expectations.py", line 30, in <module>
    from great_expectations.checkpoint.types.checkpoint_result import CheckpointResult
ModuleNotFoundError: No module named 'great_expectations.checkpoint.types'
[2025-02-22T09:11:34.675+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/gx.py
[2025-02-22T09:11:34.695+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/gx.py took 2.424 seconds
[2025-02-22T09:12:04.864+0000] {processor.py:157} INFO - Started process (PID=1417) to work on /opt/airflow/dags/gx.py
[2025-02-22T09:12:04.865+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/gx.py for tasks to queue
[2025-02-22T09:12:04.867+0000] {logging_mixin.py:151} INFO - [2025-02-22T09:12:04.867+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/gx.py
[2025-02-22T09:12:06.710+0000] {logging_mixin.py:151} INFO - [2025-02-22T09:12:06.709+0000] {warnings.py:109} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:103: UserWarning: You have an incompatible version of 'pyarrow' installed (11.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
  warn_incompatible_dep(
[2025-02-22T09:12:07.294+0000] {logging_mixin.py:151} INFO - [2025-02-22T09:12:07.292+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/gx.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gx.py", line 3, in <module>
    from great_expectations_provider.operators.great_expectations import (
  File "/home/airflow/.local/lib/python3.8/site-packages/great_expectations_provider/operators/great_expectations.py", line 30, in <module>
    from great_expectations.checkpoint.types.checkpoint_result import CheckpointResult
ModuleNotFoundError: No module named 'great_expectations.checkpoint.types'
[2025-02-22T09:12:07.295+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/gx.py
[2025-02-22T09:12:07.309+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/gx.py took 2.448 seconds
[2025-02-22T09:12:37.516+0000] {processor.py:157} INFO - Started process (PID=1438) to work on /opt/airflow/dags/gx.py
[2025-02-22T09:12:37.518+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/gx.py for tasks to queue
[2025-02-22T09:12:37.523+0000] {logging_mixin.py:151} INFO - [2025-02-22T09:12:37.522+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/gx.py
[2025-02-22T09:12:39.207+0000] {logging_mixin.py:151} INFO - [2025-02-22T09:12:39.206+0000] {warnings.py:109} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:103: UserWarning: You have an incompatible version of 'pyarrow' installed (11.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
  warn_incompatible_dep(
[2025-02-22T09:12:39.749+0000] {logging_mixin.py:151} INFO - [2025-02-22T09:12:39.747+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/gx.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gx.py", line 3, in <module>
    from great_expectations_provider.operators.great_expectations import (
  File "/home/airflow/.local/lib/python3.8/site-packages/great_expectations_provider/operators/great_expectations.py", line 30, in <module>
    from great_expectations.checkpoint.types.checkpoint_result import CheckpointResult
ModuleNotFoundError: No module named 'great_expectations.checkpoint.types'
[2025-02-22T09:12:39.750+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/gx.py
[2025-02-22T09:12:39.768+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/gx.py took 2.259 seconds
[2025-02-22T09:13:09.933+0000] {processor.py:157} INFO - Started process (PID=1459) to work on /opt/airflow/dags/gx.py
[2025-02-22T09:13:09.934+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/gx.py for tasks to queue
[2025-02-22T09:13:09.936+0000] {logging_mixin.py:151} INFO - [2025-02-22T09:13:09.936+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/gx.py
[2025-02-22T09:13:11.650+0000] {logging_mixin.py:151} INFO - [2025-02-22T09:13:11.650+0000] {warnings.py:109} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:103: UserWarning: You have an incompatible version of 'pyarrow' installed (11.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
  warn_incompatible_dep(
[2025-02-22T09:13:12.201+0000] {logging_mixin.py:151} INFO - [2025-02-22T09:13:12.200+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/gx.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gx.py", line 3, in <module>
    from great_expectations_provider.operators.great_expectations import (
  File "/home/airflow/.local/lib/python3.8/site-packages/great_expectations_provider/operators/great_expectations.py", line 30, in <module>
    from great_expectations.checkpoint.types.checkpoint_result import CheckpointResult
ModuleNotFoundError: No module named 'great_expectations.checkpoint.types'
[2025-02-22T09:13:12.202+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/gx.py
[2025-02-22T09:13:12.222+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/gx.py took 2.292 seconds
[2025-02-22T09:13:42.385+0000] {processor.py:157} INFO - Started process (PID=1480) to work on /opt/airflow/dags/gx.py
[2025-02-22T09:13:42.386+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/gx.py for tasks to queue
[2025-02-22T09:13:42.388+0000] {logging_mixin.py:151} INFO - [2025-02-22T09:13:42.388+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/gx.py
[2025-02-22T09:13:44.209+0000] {logging_mixin.py:151} INFO - [2025-02-22T09:13:44.209+0000] {warnings.py:109} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:103: UserWarning: You have an incompatible version of 'pyarrow' installed (11.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
  warn_incompatible_dep(
[2025-02-22T09:13:44.857+0000] {logging_mixin.py:151} INFO - [2025-02-22T09:13:44.856+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/gx.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gx.py", line 3, in <module>
    from great_expectations_provider.operators.great_expectations import (
  File "/home/airflow/.local/lib/python3.8/site-packages/great_expectations_provider/operators/great_expectations.py", line 30, in <module>
    from great_expectations.checkpoint.types.checkpoint_result import CheckpointResult
ModuleNotFoundError: No module named 'great_expectations.checkpoint.types'
[2025-02-22T09:13:44.858+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/gx.py
[2025-02-22T09:13:44.876+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/gx.py took 2.494 seconds
[2025-02-22T09:14:15.054+0000] {processor.py:157} INFO - Started process (PID=1501) to work on /opt/airflow/dags/gx.py
[2025-02-22T09:14:15.055+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/gx.py for tasks to queue
[2025-02-22T09:14:15.057+0000] {logging_mixin.py:151} INFO - [2025-02-22T09:14:15.057+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/gx.py
[2025-02-22T09:14:16.970+0000] {logging_mixin.py:151} INFO - [2025-02-22T09:14:16.969+0000] {warnings.py:109} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:103: UserWarning: You have an incompatible version of 'pyarrow' installed (11.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
  warn_incompatible_dep(
[2025-02-22T09:14:17.592+0000] {logging_mixin.py:151} INFO - [2025-02-22T09:14:17.591+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/gx.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gx.py", line 3, in <module>
    from great_expectations_provider.operators.great_expectations import (
  File "/home/airflow/.local/lib/python3.8/site-packages/great_expectations_provider/operators/great_expectations.py", line 30, in <module>
    from great_expectations.checkpoint.types.checkpoint_result import CheckpointResult
ModuleNotFoundError: No module named 'great_expectations.checkpoint.types'
[2025-02-22T09:14:17.593+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/gx.py
[2025-02-22T09:14:17.623+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/gx.py took 2.572 seconds
[2025-02-22T09:14:47.699+0000] {processor.py:157} INFO - Started process (PID=1522) to work on /opt/airflow/dags/gx.py
[2025-02-22T09:14:47.700+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/gx.py for tasks to queue
[2025-02-22T09:14:47.702+0000] {logging_mixin.py:151} INFO - [2025-02-22T09:14:47.702+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/gx.py
[2025-02-22T09:14:49.437+0000] {logging_mixin.py:151} INFO - [2025-02-22T09:14:49.437+0000] {warnings.py:109} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:103: UserWarning: You have an incompatible version of 'pyarrow' installed (11.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
  warn_incompatible_dep(
[2025-02-22T09:14:49.958+0000] {logging_mixin.py:151} INFO - [2025-02-22T09:14:49.957+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/gx.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gx.py", line 3, in <module>
    from great_expectations_provider.operators.great_expectations import (
  File "/home/airflow/.local/lib/python3.8/site-packages/great_expectations_provider/operators/great_expectations.py", line 30, in <module>
    from great_expectations.checkpoint.types.checkpoint_result import CheckpointResult
ModuleNotFoundError: No module named 'great_expectations.checkpoint.types'
[2025-02-22T09:14:49.959+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/gx.py
[2025-02-22T09:14:49.978+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/gx.py took 2.282 seconds
[2025-02-22T09:15:20.243+0000] {processor.py:157} INFO - Started process (PID=1549) to work on /opt/airflow/dags/gx.py
[2025-02-22T09:15:20.245+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/gx.py for tasks to queue
[2025-02-22T09:15:20.267+0000] {logging_mixin.py:151} INFO - [2025-02-22T09:15:20.265+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/gx.py
[2025-02-22T09:15:24.539+0000] {logging_mixin.py:151} INFO - [2025-02-22T09:15:24.536+0000] {warnings.py:109} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:103: UserWarning: You have an incompatible version of 'pyarrow' installed (11.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
  warn_incompatible_dep(
[2025-02-22T09:15:25.752+0000] {logging_mixin.py:151} INFO - [2025-02-22T09:15:25.745+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/gx.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gx.py", line 3, in <module>
    from great_expectations_provider.operators.great_expectations import (
  File "/home/airflow/.local/lib/python3.8/site-packages/great_expectations_provider/operators/great_expectations.py", line 30, in <module>
    from great_expectations.checkpoint.types.checkpoint_result import CheckpointResult
ModuleNotFoundError: No module named 'great_expectations.checkpoint.types'
[2025-02-22T09:15:25.754+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/gx.py
[2025-02-22T09:15:25.825+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/gx.py took 5.597 seconds
[2025-02-22T09:15:56.206+0000] {processor.py:157} INFO - Started process (PID=1569) to work on /opt/airflow/dags/gx.py
[2025-02-22T09:15:56.209+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/gx.py for tasks to queue
[2025-02-22T09:15:56.215+0000] {logging_mixin.py:151} INFO - [2025-02-22T09:15:56.214+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/gx.py
[2025-02-22T09:15:58.727+0000] {logging_mixin.py:151} INFO - [2025-02-22T09:15:58.725+0000] {warnings.py:109} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:103: UserWarning: You have an incompatible version of 'pyarrow' installed (11.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
  warn_incompatible_dep(
[2025-02-22T09:20:11.162+0000] {processor.py:157} INFO - Started process (PID=45) to work on /opt/airflow/dags/gx.py
[2025-02-22T09:20:11.164+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/gx.py for tasks to queue
[2025-02-22T09:20:11.169+0000] {logging_mixin.py:151} INFO - [2025-02-22T09:20:11.167+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/gx.py
[2025-02-22T09:20:15.766+0000] {logging_mixin.py:151} INFO - [2025-02-22T09:20:15.765+0000] {warnings.py:109} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:103: UserWarning: You have an incompatible version of 'pyarrow' installed (11.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
  warn_incompatible_dep(
[2025-02-22T09:20:16.635+0000] {logging_mixin.py:151} INFO - [2025-02-22T09:20:16.632+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/gx.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gx.py", line 3, in <module>
    from great_expectations_provider.operators.great_expectations import (
  File "/home/airflow/.local/lib/python3.8/site-packages/great_expectations_provider/operators/great_expectations.py", line 30, in <module>
    from great_expectations.checkpoint.types.checkpoint_result import CheckpointResult
ModuleNotFoundError: No module named 'great_expectations.checkpoint.types'
[2025-02-22T09:20:16.636+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/gx.py
[2025-02-22T09:20:16.672+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/gx.py took 5.515 seconds
[2025-02-22T09:20:46.769+0000] {processor.py:157} INFO - Started process (PID=73) to work on /opt/airflow/dags/gx.py
[2025-02-22T09:20:46.770+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/gx.py for tasks to queue
[2025-02-22T09:20:46.778+0000] {logging_mixin.py:151} INFO - [2025-02-22T09:20:46.777+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/gx.py
[2025-02-22T09:20:49.262+0000] {logging_mixin.py:151} INFO - [2025-02-22T09:20:49.261+0000] {warnings.py:109} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:103: UserWarning: You have an incompatible version of 'pyarrow' installed (11.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
  warn_incompatible_dep(
[2025-02-22T09:20:50.029+0000] {logging_mixin.py:151} INFO - [2025-02-22T09:20:50.027+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/gx.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gx.py", line 3, in <module>
    from great_expectations_provider.operators.great_expectations import (
  File "/home/airflow/.local/lib/python3.8/site-packages/great_expectations_provider/operators/great_expectations.py", line 30, in <module>
    from great_expectations.checkpoint.types.checkpoint_result import CheckpointResult
ModuleNotFoundError: No module named 'great_expectations.checkpoint.types'
[2025-02-22T09:20:50.029+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/gx.py
[2025-02-22T09:20:50.088+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/gx.py took 3.329 seconds
[2025-02-22T09:21:20.290+0000] {processor.py:157} INFO - Started process (PID=94) to work on /opt/airflow/dags/gx.py
[2025-02-22T09:21:20.292+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/gx.py for tasks to queue
[2025-02-22T09:21:20.311+0000] {logging_mixin.py:151} INFO - [2025-02-22T09:21:20.308+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/gx.py
[2025-02-22T09:21:22.712+0000] {logging_mixin.py:151} INFO - [2025-02-22T09:21:22.711+0000] {warnings.py:109} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:103: UserWarning: You have an incompatible version of 'pyarrow' installed (11.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
  warn_incompatible_dep(
[2025-02-22T09:21:23.283+0000] {logging_mixin.py:151} INFO - [2025-02-22T09:21:23.282+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/gx.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gx.py", line 3, in <module>
    from great_expectations_provider.operators.great_expectations import (
  File "/home/airflow/.local/lib/python3.8/site-packages/great_expectations_provider/operators/great_expectations.py", line 30, in <module>
    from great_expectations.checkpoint.types.checkpoint_result import CheckpointResult
ModuleNotFoundError: No module named 'great_expectations.checkpoint.types'
[2025-02-22T09:21:23.284+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/gx.py
[2025-02-22T09:21:23.304+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/gx.py took 3.029 seconds
[2025-02-22T09:21:53.508+0000] {processor.py:157} INFO - Started process (PID=115) to work on /opt/airflow/dags/gx.py
[2025-02-22T09:21:53.509+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/gx.py for tasks to queue
[2025-02-22T09:21:53.511+0000] {logging_mixin.py:151} INFO - [2025-02-22T09:21:53.510+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/gx.py
[2025-02-22T09:21:54.953+0000] {logging_mixin.py:151} INFO - [2025-02-22T09:21:54.952+0000] {warnings.py:109} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:103: UserWarning: You have an incompatible version of 'pyarrow' installed (11.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
  warn_incompatible_dep(
[2025-02-22T09:21:55.452+0000] {logging_mixin.py:151} INFO - [2025-02-22T09:21:55.450+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/gx.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gx.py", line 3, in <module>
    from great_expectations_provider.operators.great_expectations import (
  File "/home/airflow/.local/lib/python3.8/site-packages/great_expectations_provider/operators/great_expectations.py", line 30, in <module>
    from great_expectations.checkpoint.types.checkpoint_result import CheckpointResult
ModuleNotFoundError: No module named 'great_expectations.checkpoint.types'
[2025-02-22T09:21:55.452+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/gx.py
[2025-02-22T09:21:55.472+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/gx.py took 1.967 seconds
[2025-02-22T09:22:25.721+0000] {processor.py:157} INFO - Started process (PID=136) to work on /opt/airflow/dags/gx.py
[2025-02-22T09:22:25.722+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/gx.py for tasks to queue
[2025-02-22T09:22:25.726+0000] {logging_mixin.py:151} INFO - [2025-02-22T09:22:25.725+0000] {dagbag.py:539} INFO - Filling up the DagBag from /opt/airflow/dags/gx.py
[2025-02-22T09:22:27.414+0000] {logging_mixin.py:151} INFO - [2025-02-22T09:22:27.413+0000] {warnings.py:109} WARNING - /home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/options.py:103: UserWarning: You have an incompatible version of 'pyarrow' installed (11.0.0), please install a version that adheres to: 'pyarrow<10.1.0,>=10.0.1; extra == "pandas"'
  warn_incompatible_dep(
[2025-02-22T09:22:28.022+0000] {logging_mixin.py:151} INFO - [2025-02-22T09:22:28.021+0000] {dagbag.py:347} ERROR - Failed to import: /opt/airflow/dags/gx.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 343, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/gx.py", line 3, in <module>
    from great_expectations_provider.operators.great_expectations import (
  File "/home/airflow/.local/lib/python3.8/site-packages/great_expectations_provider/operators/great_expectations.py", line 30, in <module>
    from great_expectations.checkpoint.types.checkpoint_result import CheckpointResult
ModuleNotFoundError: No module named 'great_expectations.checkpoint.types'
[2025-02-22T09:22:28.023+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/gx.py
[2025-02-22T09:22:28.044+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/gx.py took 2.326 seconds
